### PR TITLE
Fix #1924: Sorting a list in the grid does not work

### LINKED ISSUE #1924: Sorting a list in the grid does not work
If a list is opened in a grid, and then sorted, it breaks, because `order()` does not support lists.

In general, lists cannot be meaningfully sorted, because they are heterogeneous, and different data types don't have comparison operators defined between them. So sorting should be disabled for lists.

(But note that dataframe is a special kind of list, which is treated specially, and in particular, is supported by `order`.)

### PR DESCRIPTION
**Pull request by int19h**
Fix a bunch of failing grid unit tests and related issues.

Add better tests for rtvs:::grid_data (not ful coverage yet, more to be added).

### CODE REVIEW

**Comment by int19h** [comment]
@MikhailArkhipov  @AlexanderSher can you take a look? I'd like to merge this in before deadline.

The new tests are incomplete - I didn't have the time to cover all the stuff - so I left the old ones for now. This means some duplication between them. I'll continue working on them once this is merged, but the primary goal is to get the necessary product changes in.

File: src/Package/Impl/DataInspect/DataSource/GridDataSource.cs [hunk 1]
```diff
@@ -31,5 +30,10 @@ internal sealed class GridDataSource {
                 }
             }
         }
+
+        public static Task<IGridData<string>> GetGridDataAsync(string expression, GridRange? gridRange, ISortOrder sortOrder = null) =>
+            GetGridDataAsync(
+                VsAppShell.Current.ExportProvider.GetExportedValue<IRSessionProvider>().GetInteractiveWindowRSession(),
```
Comment (AlexanderSher) [inline src/Package/Impl/DataInspect/DataSource/GridDataSource.cs]: Better access it through IWorkflowProvider

File: src/Package/Impl/DataInspect/VisualGrid/SortOrder.cs [hunk 2]
```diff
@@ -54,6 +47,10 @@ internal sealed class SortOrder : ISortOrder {
             }
         }
 
+        public void Add(ColumnSortOrder order) {
+            _sortOrderList.Add(order);
```
Comment (AlexanderSher) [inline src/Package/Impl/DataInspect/VisualGrid/SortOrder.cs]: Do we need to check if `ColumnSortOrder` is in the list already?

File: src/Package/Impl/DataInspect/DataSource/GridDataSource.cs (hunk 1 above)
Comment (int19h) [inline src/Package/Impl/DataInspect/DataSource/GridDataSource.cs]: This is the way that it was accessed originally before I split this up. There's really a lot to refactor here - e.g. this class shouldn't even have this overload at all, the caller should just supply session - but for now I'd just like to fix the issues / failing tests.

File: src/Package/TestApp/Data/GridDataTest.cs [hunk 3]
```diff
@@ -0,0 +1,257 @@
...
+        }
+
+        private static IEnumerable<T> ToEnumerable<T>(IRange<T> range) {
+            int start = range.Range.Start, end = start + range.Range.Count;
+            for (int i = start; i < end; ++i) {
+                yield return range[i];
+            }
+        }
+
+        private void ShouldEqual<T>(IGrid<T> actual, T[,] expected) {
```
Comment (AlexanderSher) [inline src/Package/TestApp/Data/GridDataTest.cs]: Can you add a task to extract this into Assertions later?

File: src/Package/Impl/DataInspect/DataSource/GridDataSource.cs (hunk 1 above)
Comment (AlexanderSher) [inline src/Package/Impl/DataInspect/DataSource/GridDataSource.cs]: ok

---
In reply to: [67211001](https://github.com/Microsoft/RTVS/pull/1927#discussion_r67211001) [](ancestors = 67211001)

File: src/Host/Client/Impl/rtvs/R/grid.R [hunk 4]
```diff
@@ -35,9 +23,19 @@ grid_data <- function(x, rows, cols, row_selector) {
   if (!missing(row_selector)) {
       x <- x[row_selector(x),, drop = FALSE]
   }
-  x <- x[rows, cols]
+  x <- x[rows, cols, drop = FALSE]
+
+  # Process and format values column by column, then flatten the resulting list of character vectors.
+  max_length <- 100 - 3
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/rtvs/R/grid.R]: Probably will need to be configurable

**Comment by MikhailArkhipov** [comment]
👍

**Comment by AlexanderSher** [comment]
:shipit:

File: src/Package/Impl/DataInspect/VisualGrid/SortOrder.cs (hunk 2 above)
Comment (int19h) [inline src/Package/Impl/DataInspect/VisualGrid/SortOrder.cs]: No, since it's purely a UI thing. Sort itself doesn't care (or break) if you sort on the same column twice - it's not particularly useful, but it's not harmful either. And doing nothing is not really a good thing, because if you sort by A, then by B, then by A, it's not the same as sorting by A then by B (which is what happens when the last add is a no-op). It should behave as sorting by B then by A. 

Also, this is basically a lower-level access hatch for the tests currently, to avoid tying it to all the visual stuff - it's not used in product code. In future refactoring, I intend it to make the only way to work with this class, and move the visual-related logic elsewhere, to the UI layer where it belongs.

File: src/Package/TestApp/Data/GridDataTest.cs (hunk 3 above)
Comment (int19h) [inline src/Package/TestApp/Data/GridDataTest.cs]: I think we need a generic assertion for 2D arrays (including non-zero bounds). Then this code just needs a small helper to convert IGrid to one. I'll file that.

File: src/Host/Client/Impl/rtvs/R/grid.R (hunk 4 above)
Comment (int19h) [inline src/Host/Client/Impl/rtvs/R/grid.R]: Definitely. I kept the hardcoded value for now because wiring up the option would touch a lot more stuff.
