### PR TITLE
Fix #541, #1191, 547

### LINKED ISSUE #541: Debugger Break command can take a very long time to break
The current implementation tries to invoke `browser()` at the next available prompt. The problem is that if the code is in a long-running computation, there may not even be a prompt for a long time, and meanwhile VS UI is blocked. Need to look at alternative ways to pause execution asynchronously; perhaps via `CallBack`.

### LINKED ISSUE #547: Breakpoints are not instantly updated
When adding or removing breakpoints, the interpreter will only see the updates after it hits the next prompt in the REPL. In other words, if code is actively running and you set a breakpoint, it won't be hit - effectively, breakpoints can only be set before debugging, or when paused on another breakpoint or after stepping, or when R code is expecting keyboard input.

### LINKED ISSUE #1191: R Host process stop: unexpected host response, Escape key after browse(), no debugger
x<-1:10
browser()
<Escape> (maybe several times...)

Trace.Fail in ProtocolError() is called.

### PR DESCRIPTION
**Pull request by int19h**
Fix #541: Debugger Break command can take a very long time to break
Fix #547: Breakpoints are not instantly updated
Fix #1191: R Host process stop: unexpected host response, Escape key after browse(), no debugger

Add support for async background evals in RHost and RSession, such that they do not require queueing requests and waiting for the next prompt to run; and use those new evals to implement debugger break.

Use async background evals to set and remove breakpoints.

Add test for debugger break/continue.

Fix OverlappingBreakpoints test to properly set/remove breakpoints while at prompt (previous behavior inadvertently relied on breakpoint creation/deletion implicitly waiting for next prompt).

### CODE REVIEW

File: src/Host/Client/Impl/Session/RSession.cs [hunk 1]
```diff
@@ -237,7 +251,7 @@ internal sealed class RSession : IRSession, IRCallbacks {
                 if (startupInfo.WorkingDirectory != null) {
                     await evaluation.SetWorkingDirectory(startupInfo.WorkingDirectory);
                 } else {
-                    await evaluation.SetDefaultWorkingDirectory();
+                await evaluation.SetDefaultWorkingDirectory();
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Session/RSession.cs]: Formatting?

File: src/Host/Client/Impl/Program.cs [hunk 2]
```diff
@@ -110,7 +110,7 @@ class Program : IRCallbacks {
 
                     if (s.StartsWith("$$", StringComparison.OrdinalIgnoreCase)) {
                         s = s.Remove(0, 1);
-                    } else if (s.StartsWith("$", StringComparison.OrdinalIgnoreCase) && isEvaluationAllowed) {
+                    } else if (s.StartsWith("$", StringComparison.OrdinalIgnoreCase)) {
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Program.cs]: StartsWithIgnoreCase ?

File: src/Host/Client/Impl/Host/RHost.cs [hunk 3]
```diff
@@ -365,7 +323,12 @@ public sealed partial class RHost : IDisposable, IRExpressionEvaluator {
                     if (message == null) {
                         return null;
                     } else if (message.RequestId != null) {
-                        return message;
+                        if (message.Name.StartsWith("=")) {
+                            ProcessEvaluationResult(message);
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Host/RHost.cs]: IgnoreCase for FxCop delight

File: src/Debugger/Test/DebugSessionExtensions.cs [hunk 4]
```diff
@@ -23,7 +23,7 @@ internal static class DebugSessionExtensions {
             EventHandler<DebugBrowseEventArgs> handler = null;
             handler = (sender, e) => {
                 session.Browse -= handler;
-                browseTcs.SetResult(true);
+                browseTcs.TrySetResult(true);
```
Comment (AlexanderSher) [inline src/Debugger/Test/DebugSessionExtensions.cs]: Do you still need this ad-hoc or you can replace it with `EventTaskSources.DebugSession.Browse`?

File: src/Host/Client/Impl/Host/RHost.cs [hunk 5]
```diff
@@ -99,7 +100,7 @@ public sealed partial class RHost : IDisposable, IRExpressionEvaluator {
             return new Message(token);
         }
 
-        private JArray CreateMessage(CancellationToken ct, out string id, string name, params object[] args) {
+        private JArray CreateMessage(out string id, string name, params object[] args) {
```
Comment (AlexanderSher) [inline src/Host/Client/Impl/Host/RHost.cs]: Do we need this method to be thread-safe?

File: src/Host/Client/Impl/Session/RSession.cs [hunk 6]
```diff
@@ -103,24 +105,36 @@ internal sealed class RSession : IRSession, IRCallbacks {
 
         public Task<IRSessionInteraction> BeginInteractionAsync(bool isVisible = true, CancellationToken cancellationToken = default(CancellationToken)) {
             if (!_isHostRunning) {
-                return CanceledInteractionTask;
+                return CanceledBeginInteractionTask;
             }
 
             RSessionRequestSource requestSource = new RSessionRequestSource(isVisible, _contexts, cancellationToken);
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Session/RSession.cs]: Since request can be executed later, can _contexts list be out of date by the time the request gets to processing?

Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Session/RSession.cs]: Also, it looks like Contexts on RSessionRequestSource doesn't need to be public anymore.

File: src/Host/Client/Impl/Host/RHost.cs [hunk 7]
```diff
@@ -375,19 +338,27 @@ public sealed partial class RHost : IDisposable, IRExpressionEvaluator {
...
                             case "?":
-                                await ShowDialog(message, allowEval, MessageButtons.YesNoCancel, CancellationTokenSource.CreateLinkedTokenSource(ct, _cancelAllCts.Token).Token);
+                                ShowDialog(message, MessageButtons.YesNoCancel, CancellationTokenSource.CreateLinkedTokenSource(ct, _cancelAllCts.Token).Token)
+                                    .SilenceException<MessageTransportException>()
+                                    .DoNotWait();
                                 break;
 
                             case "??":
-                                await ShowDialog(message, allowEval, MessageButtons.YesNo, CancellationTokenSource.CreateLinkedTokenSource(ct, _cancelAllCts.Token).Token);
+                                ShowDialog(message, MessageButtons.YesNo, CancellationTokenSource.CreateLinkedTokenSource(ct, _cancelAllCts.Token).Token)
```
Comment (AlexanderSher) [inline src/Host/Client/Impl/Host/RHost.cs]: `ShowDialog` has 2 awaits - `await _callbacks.ShowDialog(contexts, s, _canEval, buttons, ct);` and `await RespondAsync(request, ct, response);` Do we want to apply `DoNotWait` for both?

File: src/Host/Client/Impl/Session/RSession.cs [hunk 8]
```diff
@@ -454,14 +461,10 @@ internal sealed class RSession : IRSession, IRCallbacks {
         /// Graph app may call Win32 API directly rather than going via R API callbacks.
         /// </summary>
         /// <returns>Pressed button code</returns>
-        async Task<MessageButtons> IRCallbacks.ShowDialog(IReadOnlyList<IRContext> contexts, string s, bool isEvaluationAllowed, MessageButtons buttons, CancellationToken ct) {
+        async Task<MessageButtons> IRCallbacks.ShowDialog(IReadOnlyList<IRContext> contexts, string s, MessageButtons buttons, CancellationToken ct) {
```
Comment (AlexanderSher) [inline src/Host/Client/Impl/Session/RSession.cs]: So `isEvaluationAllowed` is always `true` now?

File: src/Host/Client/Impl/Session/RSession.cs [hunk 9]
```diff
@@ -103,24 +105,36 @@ internal sealed class RSession : IRSession, IRCallbacks {
...
             }
 
             var source = new RSessionEvaluationSource(isMutating, cancellationToken);
             _pendingEvaluationSources.Post(source);
 
-            return _isHostRunning ? source.Task : CanceledEvaluationTask;
+            return _isHostRunning ? source.Task : CanceledBeginEvaluationTask;
+        }
+
+        public async Task<REvaluationResult> EvaluateAsync(string expression, REvaluationKind kind, CancellationToken ct = default(CancellationToken)) {
```
Comment (AlexanderSher) [inline src/Host/Client/Impl/Session/RSession.cs]: Do you need `async\await` here?

Comment (AlexanderSher) [inline src/Host/Client/Impl/Session/RSession.cs]: So we allow to call `EvaluateAsync` outside of queue?

File: src/Host/Client/Impl/Host/RHost.cs (hunk 5 above)
Comment (int19h) [inline src/Host/Client/Impl/Host/RHost.cs]: Good catch, we do now.

File: src/Host/Client/Impl/Session/RSession.cs (hunk 6 above)
Comment (int19h) [inline src/Host/Client/Impl/Session/RSession.cs]: Good catch. Weird, though, that we haven't seem to run into this before. @AlexanderSher, is this a problem, or are we missing something?

File: src/Host/Client/Impl/Host/RHost.cs (hunk 7 above)
Comment (int19h) [inline src/Host/Client/Impl/Host/RHost.cs]: We have to, otherwise the loop won't process further incoming messages. Since the R inner loop won't move forward until it gets a response, it would seem okay?

File: src/Host/Client/Impl/Session/RSession.cs (hunk 8 above)
Comment (int19h) [inline src/Host/Client/Impl/Session/RSession.cs]: Yes, in a sense that you can call `EvaluateAsync` at any time now. There's still a queue on the host side, and if there's an active eval that is not interruptible/reentrant, other evals will not be run in the middle of it. But they will not fail, either - they'll just stay in the queue, and run at the next available opportunity.

File: src/Host/Client/Impl/Session/RSession.cs (hunk 9 above)
Comment (int19h) [inline src/Host/Client/Impl/Session/RSession.cs]: It's there to write a `try`/`catch` that converts `MessageTransportException` when host suddenly goes down to cancellation.

File: src/Host/Client/Impl/Session/RSession.cs (hunk 6 above)
Comment (AlexanderSher) [inline src/Host/Client/Impl/Session/RSession.cs]: That can be a problem. I think we haven't run into this because we don't have cases when more than one request is scheduled.

File: src/Debugger/Test/DebugSessionExtensions.cs (hunk 4 above)
Comment (int19h) [inline src/Debugger/Test/DebugSessionExtensions.cs]: Funnily enough, with this change, it will no longer work. The problem here was that `Browse` was actually raised more than once in some cases, second time being while the first handler is still running, and so `SetResult` was blowing up. So far as I can see, `EventTaskSource` doesn't even try to handle this case. I'm not sure if it should? But I could fix it there and then use it here.

File: src/Host/Client/Impl/Session/RSession.cs (hunk 6 above)
Comment (int19h) [inline src/Host/Client/Impl/Session/RSession.cs]: Okay. Since this isn't part of this change, can you file a bug? And I'll address it in a separate PR to keep things clean.

File: src/Host/Client/Impl/Session/RSession.cs (hunk 8 above)
Comment (AlexanderSher) [inline src/Host/Client/Impl/Session/RSession.cs]: So evaluation can be requested when host is in one state and get received when it is in the different state?

Comment (int19h) [inline src/Host/Client/Impl/Session/RSession.cs]: Absolutely. That's the whole point of the change (and the corresponding host change) - that evals can be fired at any moment, and will be serviced ASAP in an asynchronous fashion.

It's also why I want to keep `BeginEvaluationAsync` and friends - this lets you do evaluations in a controlled context, and check the context before running the eval. However, we have  evals all around that don't actually need this, and that suffer from the constraints that `BeginEvaluationAsync` model with the queue imposes - setting/removing breakpoints was one example of that, but I'm sure there are more similar cases.

**Comment by int19h** [comment]
I've addressed the feedback that doesn't have any open questions.

File: src/Debugger/Test/DebugSessionExtensions.cs (hunk 4 above)
Comment (AlexanderSher) [inline src/Debugger/Test/DebugSessionExtensions.cs]: EventTaskSource waits for only one event notification. Do you mean that here you need to wait for 1 or 2?

Comment (int19h) [inline src/Debugger/Test/DebugSessionExtensions.cs]: Looks like I've missed the part in `EventTaskSource` where it ensures safety if event is raised again while handler is already running. I'll make it use that.

**Comment by int19h** [comment]
Switched to `EventTaskSource`, and added support for `Mutated` event.

**Comment by MikhailArkhipov** [comment]
:+1:

**Comment by AlexanderSher** [comment]
:+1:
