### PR TITLE
Two bug fixes

### LINKED ISSUE #2722: Use host load information retrieval to track connection state
Per @AlexanderSher 

```
Since we have this code that pings broker all the time, I'd rather move 
it into RSessionProvider and raise an event every time it receives a message. 
It will allow us to get rid of the expensive 
RSessionProvider.RSessionOnDisconnectedAsync
```

### LINKED ISSUE #2749: Switching sessions should only be switching primary (REPL)
Intellisense session will be re-created as needed. Package manager should auto-close (simpler) when targets switch or should auto-update itself.

### PR DESCRIPTION
**Pull request by AlexanderSher**
- Fix #2749: Switching sessions should only be switching primary (REPL)
- Fix #2722: Use host load information retrieval to track connection state
- Part of the fix for #2070: Save As... does not change file name

### CODE REVIEW

File: src/Host/Client/Impl/Session/RSessionProvider.cs [hunk 1]
```diff
@@ -326,26 +298,26 @@ public class RSessionProvider : IRSessionProvider {
...
-
-            public Task<REvaluationResult> EvaluateAsync(string expression, REvaluationKind kind, CancellationToken cancellationToken = new CancellationToken()) {
-                return _evaluation.EvaluateAsync(expression, kind, cancellationToken);
+        private async Task UpdateHostLoadAsync(CancellationToken ct = default(CancellationToken)) {
+            HostLoad hostLoad;
+            using (await _connectArwl.ReaderLockAsync(ct)) {
+                try {
+                    hostLoad = await Broker.GetHostInformationAsync<HostLoad>(ct);
+                } catch (RHostDisconnectedException) {
+                    hostLoad = null;
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: You can just init it to null

**Comment by MikhailArkhipov** [comment]
👍
