### PR TITLE
Fix #1519 Crash in PlotContentProvider

### LINKED ISSUE #1519: Crash in PlotContentProvider
```
System events:
Time: 2016-04-08T14:40:45
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Threading.Tasks.TaskCanceledException
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.R.Package.Plots.PlotContentProvider+<ApplyNewSize>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.R.Package.Plots.PlotContentProvider+<RSession_Connected>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

### PR DESCRIPTION
**Pull request by huguesv**
This is one case where we didn't use DoNotWait, so I added the equivalent catch handlers.

### CODE REVIEW

File: src/Package/Impl/Plots/PlotContentProvider.cs [hunk 1]
```diff
@@ -31,7 +31,9 @@ internal sealed class PlotContentProvider : IPlotContentProvider {
         private async void RSession_Connected(object sender, EventArgs e) {
             // Let the host know the size of plot window
             if (_lastPixelWidth >= 0 && _lastPixelHeight >= 0) {
-                await ApplyNewSize();
+                try {
+                    await ApplyNewSize();
+                } catch (OperationCanceledException) { } catch (MessageTransportException) { } catch (RException) { }
```
Comment (int19h) [inline src/Package/Impl/Plots/PlotContentProvider.cs]: Do you really want to catch `RException` here? It would indicate an actual eval failure, which is usually a bug and not expected. Or is there some known case where eval can fail here and it is expected?

Comment (huguesv) [inline src/Package/Impl/Plots/PlotContentProvider.cs]: It's for R library errors like "invalid graphics state" and such.

From DoNotWait:
```
        public static void DoNotWait(System.Threading.Tasks.Task task) {
            // Errors like invalid graphics state which go to the REPL stderr will come back
            // in an Microsoft.R.Host.Client.RException, and we don't need to do anything with them,
            // as the user can see them in the REPL.
            task.SilenceException<MessageTransportException>()
                .SilenceException<Microsoft.R.Host.Client.RException>()
                .DoNotWait();
        }
```

Comment (int19h) [inline src/Package/Impl/Plots/PlotContentProvider.cs]: I don't think we're still doing it, actually, if you're doing interactions - i.e. stderr output should no longer translate to `RException` from `RespondAsync`. @AlexanderSher, is that right?

Comment (AlexanderSher) [inline src/Package/Impl/Plots/PlotContentProvider.cs]: Yes, error output just printed out in different color.

Comment (int19h) [inline src/Package/Impl/Plots/PlotContentProvider.cs]: Amusingly, nothing is actually throwing `RException` anywhere in the code now.

Comment (huguesv) [inline src/Package/Impl/Plots/PlotContentProvider.cs]: Shall I remove `RException` class and all the catches for it?

Comment (int19h) [inline src/Package/Impl/Plots/PlotContentProvider.cs]: I would like to appropriate that exception for failing evals sometime later. Right now `EvaluateAsync` never throws but rather just returns `REvaluationResult`, which you then have to check... and every place that uses it ends up doing that same check over and over again (or sometimes forget to do so, resulting in errors being silently swallowed). So I'd like to add some helper for `EvaluateAsync` that would just throw, and this would be the type that it'll throw.

But all places that currently catch `RException` are no-ops, and are a leftover from the time when interactions did throw. So it should be safe to remove all the catches.

Comment (huguesv) [inline src/Package/Impl/Plots/PlotContentProvider.cs]: Okay, will do that.

Comment (huguesv) [inline src/Package/Impl/Plots/PlotContentProvider.cs]: Done

**Comment by huguesv** [comment]
Removed all references to RException, but left that exception class in as requested.

**Comment by int19h** [comment]
:+1:
