### PR TITLE
Workspace fixes

### LINKED ISSUE #2632: Test connection does not work when supplying just the machine name
Since we only append protocol and port on Save

### LINKED ISSUE #2634: Delete connection should show confirmation dialog
Accidental clicking removes it and user may have problem recalling the machine name

### LINKED ISSUE #2635: Trailing space in the machine name make 'Save' disabled
Paste `KANADIG-RSRV ` (note trailing space). Save is disabled - it is confusing since it is unclear why as everything appears OK. Delete trailing space - Save is now enabled.

### PR DESCRIPTION
**Pull request by huguesv**
Fix #2632 Test connection does not work when supplying just the machine name
Fix #2634 Delete connection should show confirmation dialog
Fix #2635 Trailing space in the machine name make 'Save' disabled

### CODE REVIEW

File: src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs [hunk 1]
```diff
@@ -183,15 +183,29 @@ internal sealed class ConnectionViewModel : BindableBase, IConnectionViewModel {
...
         }
 
-       public string GetCompletePath() {
+        public void PathEditCompleted() {
+            // After the user is done editing the path, we fix it up automatically
+            Path = GetCompletePath();
+
+            // Conveniently populate the name, if the user directly edited the path
+            // without specifying a name.
+            if (string.IsNullOrWhiteSpace(Name)) {
```
Comment (int19h) [inline src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs]: One catch here is that the first time they leave focus, we'll auto-generate the name, but if they later update the URI the name will stay as is. I think this should rather check if the name is empty or looks like it was auto-generated (from the URI before the edit), and update it in the latter case also.

Comment (huguesv) [inline src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs]: Good idea, I'll change it.

Comment (huguesv) [inline src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs]: Oh wait, I don't know what the previous path was, it's already been updated.

Comment (int19h) [inline src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs]: Can the old path be stashed away somewhere?

Comment (int19h) [inline src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs]: Actually, maybe it's better to split this away from here, and instead handle it in TextChanged event (or whatever it's called), rather than on LostFocus. That way, you'll see the name update (if it was empty or auto-generated) directly as you're typing, which I think will look nicer, and it should also be easier to get the old property value in that event.

Comment (int19h) [inline src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs]: (but the URL fixup should still be on focus loss)

**Comment by huguesv** [comment]
Making the name track whatever was typed was problematic, once the typed path was auto-completed.
Instead, I ended up changing it so that the name tracks the host name. So you can come in later and edit an old connection by changing the host name, and the name will match it if it was previously automatically generated.

**Comment by int19h** [comment]
I think this is actually even better - hostname by itself is what most people will care about, and makes a more descriptive label.

File: src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs [hunk 2]
```diff
@@ -183,15 +187,56 @@ internal sealed class ConnectionViewModel : BindableBase, IConnectionViewModel {
...
+
+            var previousProposedName = GetProposedName(previousPath);
+            var currentProposedName = GetProposedName(currentPath);
+
+            // Avoid changing anything if the edit
+            // has no effect on the name (like changing the path's port)
+            if (previousProposedName != currentProposedName) {
+                // Check if the name was calculated from the previous path
+                var currentName = Name ?? string.Empty;
+                if (string.IsNullOrEmpty(currentName) || string.Compare(currentName, previousProposedName, StringComparison.CurrentCultureIgnoreCase) == 0) {
```
Comment (int19h) [inline src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs]: I believe we have `EqualsIgnoreCase` extension method on strings somewhere.

Comment (int19h) [inline src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs]: But also, does this need to ignore case? It feels like the only time when it'd be different is if the user manually edited it to make the case differ, in which case it might be better to not get in the way.

Comment (huguesv) [inline src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs]: I can go either way, I have tried both. It felt like it may be more annoying not to track the new name, then to lose a mostly insignificant case change.

Comment (int19h) [inline src/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionViewModel.cs]: I don't really have a strong opinion on it either way.

**Comment by int19h** [comment]
👍

**Comment by AlexanderSher** [comment]
👍
