### PR TITLE
Several bug fixes

### LINKED ISSUE #2360: While switching between connections I can type under the modal window

### LINKED ISSUE #2431: Assert on Reset of remote session
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Exception in RInteractiveEvaluator.ResetAsync
System.ObjectDisposedException: Cannot access a disposed object.

Object name: 'Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket'.

   at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.ThrowIfDisposed()

   at Microsoft.AspNetCore.WebSockets.Protocol.CommonWebSocket.<CloseOutputAsync>d__42.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.R.Host.Client.WebSocketMessageTransport.<CloseAsync>d__4.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.R.Host.Client.RHost.<Disconnect......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

I had tried to start help, but it was stuck so I interrupted REPL (twice).  Then I hit reset.

image

### LINKED ISSUE #2436: Failed to connect to remote, it connected to local instead
I clicked on connect next to ddhuvalo086.  It didn't complain, but it connected to local instead.  See how the title bar of REPL disagrees with status bar/connection mgr.

image

RTVS is on latest sources from master.  ddhuvalo86 remote services is from yesterday's build.

### PR DESCRIPTION
**Pull request by AlexanderSher**
- Fix #2436: Failed to connect to remote, it connected to local instead
- Fix #2431: Assert on Reset of remote session
- Fix #2360: While switching between connections I can type under the modal window

### CODE REVIEW

File: src/Common/Core/Impl/Shell/ICoreShell.cs [hunk 1]
```diff
@@ -61,13 +61,25 @@ public interface ICoreShell : ICompositionCatalog {
         /// Shows progress bar that blocks hosting shell
         /// </summary>
         /// <returns></returns>
-        ProgressBarSession ShowProgressBar(string waitMessage, int delayToShowDialogMs = 0);
+        void ShowProgressBar(Func<CancellationToken, System.Threading.Tasks.Task> method, string waitMessage, int delayToShowDialogMs = 0);
```
Comment (AlexanderSher) [inline src/Common/Core/Impl/Shell/ICoreShell.cs]: Sure

**Comment by AlexanderSher** [comment]
Ping

**Comment by MikhailArkhipov** [comment]
👍
