### PR TITLE
Fix connection manager bugs

### LINKED ISSUE #2807: No way to switch between connections with identical path
Case 1:
- Create 2 identical connections with just different name
- Connect to first one
- Click "Connect" on the second one

Nothing happens. While not trying to reconnect to the same connection is correct, user should be either notified about that or active connection should change do the new one.

Case 2:
- Create 2 identical connections with different name and different command line arguments
- Connect to first one
- Click "Connect" on the second one

Nothing happens. These connections are different, so we should switch and update command line parameters for the newly started sessions

### LINKED ISSUE #2845: When connection is deleted it is not really disconnected
Deleted connection to the server (while connected). Operation on REPL says disconnected, but title of the window still lists the URL and attemts to reset REPL actually tries to reconnect.

image

### LINKED ISSUE #2898: Package manager does not update after uninstall
I installed 'shiny' in REPL. Opened package manager, searched for 'shiny' hit uninstall. After the package was removed, package manager did not update. I verified that the package was removed.

### PR DESCRIPTION
**Pull request by AlexanderSher**
- Fix #2807: No way to switch between connections with identical path
- Fix #2845: When connection is deleted it is not really disconnected
- Fix #2898: Package manager does not update after uninstall

### CODE REVIEW

File: src/Host/Client/Impl/Host/BrokerClient.cs [hunk 1]
```diff
@@ -46,17 +49,20 @@ internal abstract class BrokerClient : IBrokerClient {
...
+        protected BrokerClient(string name, Uri brokerUri, string rCommandLineArguments, string interpreterId, ICredentialsDecorator credentials, IActionLog log, IConsole console) {
             Name = name;
             Uri = brokerUri;
             Log = log;
 
+            RCommandLineArguments = rCommandLineArguments?.Trim() ?? string.Empty;
             _interpreterId = interpreterId;
             _credentials = credentials;
             _console = console;
+            _parametersHash = CalculateAdditionalParametersHash();
```
Comment (AlexanderSher) [inline src/Host/Client/Impl/Host/BrokerClient.cs]: `_parametersHash` is required to distinguish different connections from the same user to the same machine for different parameters (command line arguments, interpreter, etc.).

Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Host/BrokerClient.cs]: Theoretically it is possible to override GetHashString on the connection and compare those.

File: src/Host/Client/Impl/Host/BrokerClient.cs [hunk 2]
```diff
@@ -109,20 +115,21 @@ internal abstract class BrokerClient : IBrokerClient {
             DisposableBag.ThrowIfDisposed();
             await TaskUtilities.SwitchToBackgroundThread();
 
+            var sessionName = connectionInfo.Name + _parametersHash;
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Host/BrokerClient.cs]: Make small `GetUniqueName`?

File: src/Host/Client/Impl/Host/BrokerClient.cs [hunk 3]
```diff
@@ -136,14 +143,42 @@ internal abstract class BrokerClient : IBrokerClient {
         protected virtual Task<Exception> HandleHttpRequestExceptionAsync(HttpRequestException exception)
             => Task.FromResult<Exception>(new RHostDisconnectedException(Resources.Error_HostNotResponding.FormatInvariant(Name, exception.Message), exception));
 
+        private string CalculateAdditionalParametersHash() {
+            if (string.IsNullOrEmpty(RCommandLineArguments)) {
+                return string.Empty;
+            }
+
+            var bytes = Encoding.Unicode.GetBytes(RCommandLineArguments);
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Host/BrokerClient.cs]: `RCommandLineArguments.GetSHA512Hash()`

File: src/Host/Client/Impl/Host/BrokerClient.cs [hunk 4]
```diff
@@ -136,14 +143,42 @@ internal abstract class BrokerClient : IBrokerClient {
...
+            }
+
+            var hashCharsLength = (int)(hashBytes.Length * 4.0d / 3.0d);
+            if (hashCharsLength % 4 != 0) {
+                hashCharsLength += 4 - hashCharsLength % 4;
+            }
+
+            var hashChars = new char[hashCharsLength];
+
+            Convert.ToBase64CharArray(hashBytes, 0, hashBytes.Length, hashChars, 0);
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Host/BrokerClient.cs]: This might be another useful extension next to `GetSHA512Hash`

File: src/Host/Client/Impl/Host/IBrokerClient.cs [hunk 5]
```diff
@@ -11,6 +11,7 @@ public interface IBrokerClient : IDisposable {
         string Name { get; }
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Host/IBrokerClient.cs]: Starts looking a lot like `ConnectionInfo`

File: src/Host/Client/Impl/Host/BrokerClient.cs (hunk 1 above)
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Host/BrokerClient.cs]: The other thing we could just add Guid to `ConnectionInfo` and use it (and persist in settings) and distinguish connections by guids.

File: src/Host/Client/Impl/Session/RSession.cs [hunk 6]
```diff
@@ -239,10 +242,10 @@ public Task StartHostAsync(RHostStartupInfo startupInfo, IRSessionCallback callb
             TaskUtilities.AssertIsOnBackgroundThread();
 
             _callback = callback;
-            _startupInfo = startupInfo;
+            _startupInfo = startupInfo ?? new RHostStartupInfo();
             RHost host;
             try {
-                var connectionInfo = new BrokerConnectionInfo(startupInfo.Name, this, startupInfo.RHostCommandLineArguments, timeout);
+                var connectionInfo = new BrokerConnectionInfo(Name, this, startupInfo.UseRHostCommandLineArguments, timeout);
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Session/RSession.cs]: So why empty/null command line args are insufficient and we need a separate flag?

File: src/Host/Client/Impl/Session/RSessionProvider.cs [hunk 7]
```diff
@@ -84,15 +84,15 @@ public class RSessionProvider : IRSessionProvider {
             Broker.Dispose();
         }
 
-        private RSession CreateRSession(Guid guid) {
-            var session = new RSession(Interlocked.Increment(ref _sessionCounter), Broker, _connectArwl.CreateExclusiveReaderLock(), () => DisposeSession(guid));
+        private RSession CreateRSession(string sessionId) {
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: If we add Guid to connection info, we can as well use it as session id

File: src/Host/Client/Impl/Session/RSessionProvider.cs [hunk 8]
```diff
@@ -145,11 +145,25 @@ public class RSessionProvider : IRSessionProvider {
...
+                }
+            }
+        }
+
+        public async Task<bool> TrySwitchBrokerAsync(string name, string path = null, string rCommandLineArguments = null, CancellationToken cancellationToken = default(CancellationToken)) {
             using (_disposeToken.Link(ref cancellationToken)) {
                 await TaskUtilities.SwitchToBackgroundThread();
 
-                var brokerClient = CreateBrokerClient(name, path, cancellationToken);
+                var brokerClient = CreateBrokerClient(name, path, rCommandLineArguments, cancellationToken);
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: Just pass IConnectionInfo?

**Comment by MikhailArkhipov** [comment]
So basically question is: like COM objects, connections can have unique guids. This way property value won't matter. Then, session ID == connection info guid. And we can pass around connection info around.

File: src/Host/Client/Impl/Host/BrokerClient.cs (hunk 4 above)
Comment (AlexanderSher) [inline src/Host/Client/Impl/Host/BrokerClient.cs]: Sure.

File: src/Host/Client/Impl/Session/RSession.cs (hunk 6 above)
Comment (AlexanderSher) [inline src/Host/Client/Impl/Session/RSession.cs]: command line args is a connection level setting. Individual sessions may or may not want to use arguments. REPL session uses args, Package Manager session doesn't need them. I'm not sure about intellisense session: command line args may contain a script that loads a package. Does it matter?

File: src/Host/Client/Impl/Host/BrokerClient.cs (hunk 1 above)
Comment (AlexanderSher) [inline src/Host/Client/Impl/Host/BrokerClient.cs]: It is already a combination of session id and `_parametersHash`. As you mentioned, `_parametersHash` is basically a connection id.

The problem with guid as a connection id is that it is random. To find matching connection, you have to either fetch data about all existing connections and find the right one, or ask broker to do it by providing all the parameters. In both cases, it requires changes in broker code and may have potential versioning issues (if we add or remove parameter). 
With hash instead of guid, it is guaranteed that for the same parameters you'll get the same id, and broker doesn't have to know anything about those parameters if they are VS or RHost specific.

File: src/Host/Client/Impl/Host/BrokerClient.cs (hunk 2 above)
Comment (AlexanderSher) [inline src/Host/Client/Impl/Host/BrokerClient.cs]: Ok

File: src/Host/Client/Impl/Session/RSessionProvider.cs (hunk 7 above)
Comment (AlexanderSher) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: No, sessions are orthogonal to connections.

Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: I'd say 45 degrees but OK. ;-)

**Comment by MikhailArkhipov** [comment]
👍

File: src/Host/Client/Impl/Host/IBrokerClient.cs (hunk 5 above)
Comment (AlexanderSher) [inline src/Host/Client/Impl/Host/IBrokerClient.cs]: Well, looks like an idea to merge these two interfaces was a bit reckless.
- IConnectionInfo has a `Path` property, which is a string. It is good for both UI and settings storage. We actually don't want to replace it with URL because we want to preserve user input after he has saved it.
- IBrokerClient has a `Uri` property, which is URI. It is good for web service operation. Also, on the level of `Host.Client` assembly we don't care about user input format. 

Equality logic is also different:
- IConnectionInfo instances are considered equal if they have identical names.
- IBrokerClient instances are considered equal if they have equal Id's.

So I'd rather not touch it for now, cause it is not that simple and also we introduce new bugs.

Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Host/IBrokerClient.cs]: Let's leave it alone then. It is probably possible to have some sort of comparable indentifications but it may be too much of a change at this point.
