### PR TITLE
Fix #2625: NRE in Variable Explorer when closing VS

### LINKED ISSUE #2625: NRE in Variable Explorer when closing VS
```
   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions.<EvaluateAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.R.Package.DataInspect.REnvironmentProvider.<RefreshEnvironmentsAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Common.Core.TaskExtensions.<>c.<DoNotWaitThreadContinuation>b__6_0(Object s)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

### PR DESCRIPTION
**Pull request by int19h**
Cancel refresh operation in REnvironmentProvider when the latter is disposed.

### CODE REVIEW

File: src/Package/Impl/DataInspect/REnvironmentProvider.cs [hunk 1]
```diff
@@ -19,7 +20,9 @@ internal class REnvironmentProvider : BindableBase, IREnvironmentProvider {
         private static readonly string[] _hiddenEnvironments = { "Autoloads", "rtvs::graphics::ide", ".rtvs" };
         private static readonly IReadOnlyList<REnvironment> _errorEnvironments = new[] { REnvironment.Error };
 
-        private IRSession _rSession;
+        private readonly DisposeToken _disposeToken = DisposeToken.Create<REnvironmentProvider>();
+        private volatile IRSession _rSession;
+        private readonly CancellationTokenSource _refreshCts = new CancellationTokenSource();
```
Comment (AlexanderSher) [inline src/Package/Impl/DataInspect/REnvironmentProvider.cs]: `_refreshCts` not used

File: src/Package/Impl/DataInspect/REnvironmentProvider.cs [hunk 2]
```diff
@@ -44,41 +51,55 @@ internal class REnvironmentProvider : BindableBase, IREnvironmentProvider {
...
+                    cancellationToken.ThrowIfCancellationRequested();
+
+                    success = true;
+                } catch (RException) {
+                } catch (OperationCanceledException) {
                 }
-                SelectedEnvironment = newSelection ?? _environments.FirstOrDefault();
-            });
+
+                VsAppShell.Current.DispatchOnUIThread(() => {
```
Comment (AlexanderSher) [inline src/Package/Impl/DataInspect/REnvironmentProvider.cs]: Why `DispatchOnUIThread` instead of `SwitchToMainThreadAsync`?

File: src/Package/Impl/DataInspect/REnvironmentProvider.cs [hunk 3]
```diff
@@ -44,41 +51,55 @@ internal class REnvironmentProvider : BindableBase, IREnvironmentProvider {
...
+                    var traceback = (await session.TracebackAsync())
+                        .Skip(1) // skip global - it's in the search path already
+                        .Select(frame => new REnvironment(frame))
+                        .Reverse();
+                    if (traceback.Any()) {
+                        envs.AddRange(traceback);
+                        envs.Add(null);
+                    }
+
+                    cancellationToken.ThrowIfCancellationRequested();
```
Comment (AlexanderSher) [inline src/Package/Impl/DataInspect/REnvironmentProvider.cs]: I'd rather pass `cancellationToken` to `TracebackAsync` and `EvaluateAsync` instead of calling `ThrowIfCancellationRequested` between those calls

File: src/Package/Impl/DataInspect/REnvironmentProvider.cs (hunk 1 above)
Comment (AlexanderSher) [inline src/Package/Impl/DataInspect/REnvironmentProvider.cs]: `_refreshCts` not used

File: src/Package/Impl/DataInspect/REnvironmentProvider.cs (hunk 2 above)
Comment (AlexanderSher) [inline src/Package/Impl/DataInspect/REnvironmentProvider.cs]: Why `DispatchOnUIThread` instead of `SwitchToMainThreadAsync`?

File: src/Package/Impl/DataInspect/REnvironmentProvider.cs (hunk 1 above)
Comment (AlexanderSher) [inline src/Package/Impl/DataInspect/REnvironmentProvider.cs]: `_refreshCts` not used

Comment (AlexanderSher) [inline src/Package/Impl/DataInspect/REnvironmentProvider.cs]: `_refreshCts` not used

File: src/Package/Impl/DataInspect/REnvironmentProvider.cs (hunk 3 above)
Comment (AlexanderSher) [inline src/Package/Impl/DataInspect/REnvironmentProvider.cs]: I'd rather pass `cancellationToken` to `TracebackAsync` and `EvaluateAsync` instead of calling `ThrowIfCancellationRequested` between those calls

Comment (int19h) [inline src/Package/Impl/DataInspect/REnvironmentProvider.cs]: Good point, I forgot they take the token :)

Comment (AlexanderSher) [inline src/Package/Impl/DataInspect/REnvironmentProvider.cs]: `SwitchToMainThreadAsync` also takes the token :)

File: src/Common/Core/Test/Fakes/Shell/TestMainThread.cs [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+
+using System;
+using System.Diagnostics.CodeAnalysis;
+using System.Threading;
+using Microsoft.Common.Core.Threading;
+using Microsoft.UnitTests.Core.Threading;
+
+namespace Microsoft.Common.Core.Test.Fakes.Shell {
+    [ExcludeFromCodeCoverage]
+    public class TestMainThread : IMainThread {
```
Comment (AlexanderSher) [inline src/Common/Core/Test/Fakes/Shell/TestMainThread.cs]: I've just added the same class :)

**Comment by AlexanderSher** [comment]
👍
