### PR TITLE
Bug fixes

### LINKED ISSUE #3186: Shortcuts don't show up in menus RTools > Windows
image

Ignore High-contrast.

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
#3186 Shortcuts don't show up in menus RTools > Windows
#3196 Logging options combo box empty (with test)
#3195 REvaluationException crashed VS
#3193 Add database connection, cancel, and it still adds it to your settings

### CODE REVIEW

**Comment by MikhailArkhipov** [comment]
Ping so I can kick build for the BB

File: src/Common/Core/Impl/Logging/Implementation/LoggingPermissions.cs [hunk 1]
```diff
@@ -89,7 +89,7 @@ public sealed class LoggingPermissions : ILoggingPermissions {
 
         private int? GetValueFromRegistry(string name, int minValue, int maxValue) {
             if(_appConstants.LocalMachineHive == null) {
-                return minValue;
+                return maxValue;
```
Comment (AlexanderSher) [inline src/Common/Core/Impl/Logging/Implementation/LoggingPermissions.cs]: Does it mean we will have `maxValue` by default?

File: src/Package/Impl/Options/Attributes/EnumTypeConverter.cs [hunk 2]
```diff
@@ -63,7 +62,7 @@ protected EnumTypeConverter(params string[] localizedDisplayNames)
         }
 
         public override object ConvertTo(ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType) {
-            if (value.GetType() == destinationType) {
+            if (value == null || value.GetType() == destinationType) {
```
Comment (AlexanderSher) [inline src/Package/Impl/Options/Attributes/EnumTypeConverter.cs]: `value?.GetType() == destinationType`

File: src/R/Editor/Impl/Data/RSessionDataObject.cs [hunk 3]
```diff
@@ -108,22 +108,24 @@ public class RSessionDataObject : IRSessionDataObject {
...
-                    AttributeCountProperty |
-                    DimProperty |
-                    FlagsProperty |
-                    (RToolsSettings.Current.EvaluateActiveBindings ? ComputedValueProperty : 0);
-                var children = await valueEvaluation.DescribeChildrenAsync(properties, RValueRepresentations.Str(MaxReprLength), MaxChildrenCount);
-                return EvaluateChildren(children);
-            }
+            try {
+                if (valueEvaluation.HasChildren) {
+                    await TaskUtilities.SwitchToBackgroundThread();
```
Comment (AlexanderSher) [inline src/R/Editor/Impl/Data/RSessionDataObject.cs]: Let's move `await TaskUtilities.SwitchToBackgroundThread();` before try/catch block, otherwise `catch` will switch to UI thread.

File: src/Common/Core/Impl/Logging/Implementation/LoggingPermissions.cs (hunk 1 above)
Comment (MikhailArkhipov) [inline src/Common/Core/Impl/Logging/Implementation/LoggingPermissions.cs]: This is test only case (no registry)

File: src/Package/Impl/Options/Attributes/EnumTypeConverter.cs (hunk 2 above)
Comment (MikhailArkhipov) [inline src/Package/Impl/Options/Attributes/EnumTypeConverter.cs]: OK

File: src/Package/Impl/Options/R/RToolsOptionsPage.cs [hunk 4]
```diff
@@ -198,19 +198,15 @@ public class RToolsOptionsPage : DialogPage {
...
             get {
-#if DEBUG
-                return _holder.GetValue<LogVerbosity>(LogVerbosity.Traffic);
-#else
-                return _holder.GetValue<LogVerbosity>(LogVerbosity.Normal);
-#endif
+                var permissions = VsAppShell.Current.Services.LoggingPermissions;
+                var value = _holder.GetValue<LogVerbosity>(permissions.MaxVerbosity);
+                value = MathExtensions.Min<LogVerbosity>(value, permissions.MaxVerbosity);
+                _holder.SetValue(value);
```
Comment (AlexanderSher) [inline src/Package/Impl/Options/R/RToolsOptionsPage.cs]: Doesn't really understand this piece. Shouldn't we restrict max value in setter?

Comment (MikhailArkhipov) [inline src/Package/Impl/Options/R/RToolsOptionsPage.cs]: This happens if value stored earlier is read by VS and set here. Earlier value may be higher than the most recently set limit in registry.

Comment (MikhailArkhipov) [inline src/Package/Impl/Options/R/RToolsOptionsPage.cs]: Or we can move this to load settings?

**Comment by karthiknadig** [comment]
👍
