### PR TITLE
Fix #1311: REPL null reference exception

### LINKED ISSUE #1311: REPL null reference exception
Using today's code from master.

Editing a line in REPL that looked like:
```
dim(a1)
```

```
        public static SnapshotPoint? MapCaretPositionFromView(ITextView textView) {
            if (!textView.Caret.InVirtualSpace) {
                SnapshotPoint caretPosition = textView.Caret.Position.BufferPosition;
                return MapPointFromView(textView, caretPosition);
            }
            return null;
        }

```
where `textView` is null.

```
>	Microsoft.R.Editor.dll!Microsoft.R.Editor.Document.REditorDocument.MapCaretPositionFromView(Microsoft.VisualStudio.Text.Editor.ITextView textView) Line 182	C#
 	Microsoft.R.Editor.dll!Microsoft.R.Editor.Signatures.SignatureHelp.UpdateCurrentParameter.AnonymousMethod__0(object o) Line 168	C#
 	Microsoft.R.Editor.dll!Microsoft.R.Editor.Tree.EditorTree.FirePostUpdateEvents(System.Collections.Generic.List<Microsoft.R.Editor.Tree.TreeChangeEventRecord> changes, bool fullParse) Line 63	C#
 	Microsoft.R.Editor.dll!Microsoft.R.Editor.Tree.TreeUpdateTask.ApplyBackgroundProcessingResults() Line 581	C#
 	Microsoft.R.Editor.dll!Microsoft.R.Editor.Tree.TreeUpdateTask.ProcessTextChanges.AnonymousMethod__38_0() Line 453	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown

```

### PR DESCRIPTION
**Pull request by MikhailArkhipov**

### CODE REVIEW

File: src/R/Editor/Impl/Signatures/SignatureHelp.cs [hunk 1]
```diff
@@ -163,10 +163,13 @@ public partial class SignatureHelp : ISignature {
                 IREditorDocument document = REditorDocument.TryFromTextBuffer(SubjectBuffer);
                 if (document != null) {
                     SnapshotPoint? p = REditorDocument.MapCaretPositionFromView(TextView);
+                    var textView = TextView; // Cache so it doesn't go away when callback is invoked.
```
Comment (AlexanderSher) [inline src/R/Editor/Impl/Signatures/SignatureHelp.cs]: Do we actually need to execute callback when TextView is null?

Comment (MikhailArkhipov) [inline src/R/Editor/Impl/Signatures/SignatureHelp.cs]: Yes. We need to re-trigger session when information fetching is done. Basically, core editor is synchronous. It calls for parameters help and we need time. So we tell it that we don't have anything and then, when information comes, trigger signature help again. 

Hugues has slower laptop this is why it doesn't repro always. The calling object is still available on faster machines.

**Comment by AlexanderSher** [comment]
:+1:

File: src/R/Editor/Impl/Signatures/SignatureHelp.cs (hunk 1 above)
Comment (MikhailArkhipov) [inline src/R/Editor/Impl/Signatures/SignatureHelp.cs]: However, in this particular case we may technically skip it since if signature is gone, probably there is no need to recalc parameter position.
