### PR TITLE
Fix #3119: ggvis sample crashes on remote

### LINKED ISSUE #3119: ggvis sample crashes on remote
```
library(ggvis)

# Make data set with categorical x
mtc <- mtcars
mtc$cyl <- factor(mtc$cyl)
mtc %>% ggvis(~cyl, ~ mpg) %>% layer_boxplots()
# Set the width of the boxes to half the space between tick marks
mtc %>% ggvis(~cyl, ~ mpg) %>% layer_boxplots(width = 0.5)

# Continuous x: boxes fill width between data values
mtcars %>% ggvis(~cyl, ~ mpg) %>% layer_boxplots()
# Setting width=0.5 makes it 0.5 wide in the data space, which is 1/4 of the
# distance between data values in this particular case.
mtcars %>% ggvis(~cyl, ~ mpg) %>% layer_boxplots(width = 0.5)
```

The code opens browser in local R in the end. On remote session terminates.

### PR DESCRIPTION
**Pull request by int19h**
Block non http:// URLs in remote sessions.

### CODE REVIEW

File: src/Host/Client/Impl/Host/RemoteBrokerClient.cs [hunk 1]
```diff
@@ -52,8 +52,14 @@ public RemoteBrokerClient(string name, BrokerConnectionInfo connectionInfo, ICor
             return host;
         }
 
-        public override Task<string> HandleUrlAsync(string url, CancellationToken cancellationToken) =>
-            WebServer.CreateWebServerAsync(url, HttpClient.BaseAddress.ToString(), Name, _services, _console, cancellationToken);
+        public override async Task<string> HandleUrlAsync(string url, CancellationToken cancellationToken) {
+            if (!url.StartsWith("http://")) {
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Host/RemoteBrokerClient.cs]: Probably `StartsWithIgnoreCase`

**Comment by MikhailArkhipov** [comment]
👍

File: src/Host/Client/Impl/Host/RemoteBrokerClient.cs (hunk 1 above)
Comment (int19h) [inline src/Host/Client/Impl/Host/RemoteBrokerClient.cs]: Yup, RFC says case-insensitive. Will fix.
