### PR TITLE
Fixes #2347 protocol errors are transmitted back to RTVS

### LINKED ISSUE #2347: Remote shiny/help crashes RTVS while handling favicon.ico requests

### PR DESCRIPTION
**Pull request by karthiknadig**
Previously favicon.ico requests would cause 404 from RHost which is normal. But the remoting code did not send this server error response back to RTVS/Browser.

### CODE REVIEW

File: src/Host/Client/Impl/BrokerServices/RemoteUriWebService.cs [hunk 1]
```diff
@@ -47,21 +47,33 @@ public class RemoteUriWebService : IRemoteUriWebService {
...
+                    response = wex.Response as HttpWebResponse;
+                } else {
+                    throw wex;
+                }
+            } finally {
+                if (response != null) {
+                    if (context.Request.IsWebSocketRequest) {
+                        Stream respStream = response.GetResponseStream();
+                        string subProtocol = response.Headers[Constants.Headers.SecWebSocketProtocol];
+                        var remoteWebSocket = CommonWebSocket.CreateClientWebSocket(respStream, subProtocol, TimeSpan.FromMinutes(10), 65335, true);
```
Comment (int19h) [inline src/Host/Client/Impl/BrokerServices/RemoteUriWebService.cs]: Can you use named arguments here, so that it's clear what the number and the boolean correspond to?

File: src/Host/Client/Impl/BrokerServices/RemoteUriWebService.cs [hunk 2]
```diff
@@ -47,21 +47,33 @@ public class RemoteUriWebService : IRemoteUriWebService {
...
+                response = (HttpWebResponse)await request.GetResponseAsync();
+            } catch (WebException wex) {
+                if(wex.Status == WebExceptionStatus.ProtocolError) {
+                    response = wex.Response as HttpWebResponse;
+                } else {
+                    throw wex;
+                }
+            } finally {
+                if (response != null) {
+                    if (context.Request.IsWebSocketRequest) {
```
Comment (int19h) [inline src/Host/Client/Impl/BrokerServices/RemoteUriWebService.cs]: This might do the wrong thing when you have a websocket request and an error response. A successful websocket request _must_ have HTTP response 101 (switching protocols). If it's any other error, the response is not a websocket stream (e.g. because the server to which the request was made doesn't support websockets), but rather just a generic HTTP response. So if you call `AcceptWebSocketAsync` on that, it'll break.

**Comment by int19h** [comment]
👍
