### PR TITLE
Bunch of fixes

### LINKED ISSUE #3349: Help/Shiny does not work on linux
I had to change the HTTP request handler. Something might have broken during the change.

### PR DESCRIPTION
**Pull request by karthiknadig**
fixes #3349.
Few other bugs discovered while testing.

### CODE REVIEW

File: src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj [hunk 1]
```diff
@@ -23,6 +23,7 @@
     <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.1" />
     <PackageReference Include="System.Net.NetworkInformation" Version="4.3.0" />
     <PackageReference Include="System.Net.Requests" Version="4.3.0" />
+    <PackageReference Include="System.Net.WebSockets.Client" Version="4.3.1" />
```
Comment (MikhailArkhipov) [inline src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj]: Does it need to be added to `<VSIXSourceItem>` in package as well as to Wix (remote setup) and `swix` in RTVS-pr?

File: src/Host/Broker/Impl/RemoteUri/RemoteUriHelper.cs [hunk 2]
```diff
@@ -22,27 +23,17 @@ public class RemoteUriHelper {
...
                     }
 
-                    var response = await client.SendAsync(request);
-                    HttpStatusCode statusCode = response.StatusCode;
-                    if (statusCode != HttpStatusCode.SwitchingProtocols) {
-                        response.Dispose();
-                    } else {
-                        string respSubProtocol = response.Headers.GetValues(Constants.Headers.SecWebSocketProtocol).FirstOrDefault();
-                        // TODO: match sub protocols.
+                    clientWebsocket.Options.KeepAliveInterval = TimeSpan.FromMinutes(10);
```
Comment (AlexanderSher) [inline src/Host/Broker/Impl/RemoteUri/RemoteUriHelper.cs]: Can we write a test for this, or it will be too complicated?

File: src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj (hunk 1 above)
Comment (karthiknadig) [inline src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj]: Doesn't look like it for this one. However, i did find one that was not added.

File: src/Host/Broker/Impl/RemoteUri/RemoteUriHelper.cs (hunk 2 above)
Comment (karthiknadig) [inline src/Host/Broker/Impl/RemoteUri/RemoteUriHelper.cs]: Work item to write tests for help and shiny: #3640
