### PR TITLE
#2060 and other fixes

### LINKED ISSUE #2060: New file does not appear in the project and AF when closing the project
Not sure if this is truly needed, but this how I got there
Install SQL tools
Install AdventureWorks DB

1. Create R project
2. Open SQL Object Explorer (View -> ...)
3. Connect to local instance / AdventureWorks
4. Right click AdventureWorks -> New Query
5. SELECT * FROM Human...
6. Save SQL in the project folder

OBSERVED: file does not appear in the project (Show all does display it)
Close solution

image

```
'path' cannot be an empty string ("") or start with the null character.
Parameter name: path

   at Microsoft.Requires.NotNullOrEmpty(String value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.PathHelper.MakeRelative(String basePath, String path)
   at Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.Utilities.PathExtensions.ToShortRelativePath(IFileSystem fileSystem, String path, String rootFolder) in F:\RTVS\src\ProjectSystem\Impl\Utilities\PathExtensions.cs:line 14
   at Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.IO.MsBuildFileSystemWatcher.FileCreated.Apply() in F:\RTVS\src\ProjectSystem\Impl\IO\MsBuildFileSystemWatcher.FileCreated.cs:line 31

```

change appears to be OK

image

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
#2060 New file does not appear in the project and AF when closing...
Reverse Ctrl+F1 and F1 bindings
Add SQL Query template
Better handle .sql files written with UTF-8 BOM
Auto-position caret at the REPL prompt on typing

### CODE REVIEW

File: src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs [hunk 1]
```diff
@@ -215,6 +215,9 @@ public sealed partial class MsBuildFileSystemWatcher : IDisposable {
 
             relativePath = PathHelper.MakeRelative(rootDirectory, fullPath);
             try {
+                if (!fileSystem.FileExists(fullPath)) {
```
Comment (AlexanderSher) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: This is really weird. How is it possible that `GetFileAttributes` fails for a newly added file?

Comment (MikhailArkhipov) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: Async stuff. Set bp in debugger, see exception catch getting hit. Repeat stepping of the same code, it succeeds. Not sure where the race is coming from.

Comment (MikhailArkhipov) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: OK, I can remove this if the exception is not causing trouble. CPS exception was caused by Link metadata and appears to go away when I remove Link property from rules. But this is more or less 'best guess'

Comment (AlexanderSher) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: Race may occur right after this method returns `true`, and there is try/catch around this block already, so calling `FileExists` is useless. But we probably need to catch `UnauthorizedAccessException` in addition to `IOException`.

Comment (MikhailArkhipov) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: Not entirely. FileExists check prevents returning false in IsFileAllowed. Returning false may actually explain when sometimes file is added, but does not appear in project explorer. Race occurs when check happens between file is deleted and then re-created. I guess the event queue is not compact i.e. create-delete-create is not collapsed into just created.

Comment (MikhailArkhipov) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: Basically - is there a harm reporting that file is allowed when it actually does not exist i.e. doing optimistic check?

Comment (AlexanderSher) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: I think that `_fileSystem.ToShortRelativePath` will throw an exception on the file that doesn't exist

Comment (MikhailArkhipov) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: OK, let me look into that.

Comment (MikhailArkhipov) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: What throws is 

```
                return filter.IsFileAllowed(relativePath, fileSystem.GetFileAttributes(fullPath));

```

specifically

```
fileSystem.GetFileAttributes
```

since the file does not exist.

Comment (AlexanderSher) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: Sure, but it is catched and method exists with false, so there can't be a popup message with exception.
I think that without debugger race happens in a different place - between this method and  `ToShortRelativePath` calls. This method returns `true`, but  `ToShortRelativePath` throws exception.

Comment (MikhailArkhipov) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: Ah, I think we are talking 3 different things since I found 3 different issues :-)

1. IsFileAllowed throwing - no popup, but I've seen file added but not showing up in Solution Explorer.
2. CPS 'not supported' exception when 'Link' metadata mismatch.
3. The popup in the beginning of the bug - yes, that is about ToShortRelativePath and I am going to look into it.

Comment (AlexanderSher) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: Hm... then the first case requires further investigation. Any `IFileSystemChange` appears in queue only after event has happened. So if `FileCreated` happened but no file was found, there should be another `FileCreated` in the queue that should add a file. Or there should be an error in the log.
Do you have logs for the #2070?

Comment (MikhailArkhipov) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: There are some attached to #2060. Basically I saw bp hit in exception, then repeating same code in debugger would succeed.

Comment (AlexanderSher) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.cs]: There are no failures. Log shows that file was added to the project msbuild:
```
[16-7-13_10-33-43]:File mirroring project after changes applied:
                   <?xml version="1.0" encoding="utf-16"?>
                   <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
                     <ItemGroup>
                       <Content Include=".Rhistory" />
                       <Content Include="adcd 1 2 3 4 5 6 7 8 9\markdown.html" />
                       <Content Include="adcd 1 2 3 4 5 6 7 8 9\markdown.rmd" />
                       <Content Include="markdown.html" />
                       <Content Include="markdown.rmd" />
                       <Content Include="query.sql" />
                       <Content Include="rproject10.rproj" />
                       <Content Include="script.R" />
                       <Content Include="script1.R" />
                       <Content Include="Script2.R" />
                       <Content Include="Settings.R" />
                       <Content Include="Settings1.R" />
                       <Content Include="SqlQuery.sql" />
                       <Content Include="SQLQuery1.sql" />
                     </ItemGroup>
                     <ItemGroup>
                       <Folder Include="adcd 1 2 3 4 5 6 7 8 9\" />
                     </ItemGroup>
                     <ItemGroup />
                   </Project>
```

**Comment by AlexanderSher** [comment]
:+1:
