### PR TITLE
Formatting and intellisense fixes

### LINKED ISSUE #2467: Formatting: if-expression on newline after <- is indented wrong
Original code:

``` r
function() {
    field <-
        if (missing(fields)) {
            function(x) TRUE;
        } else {
            function(x) x %in% fields
        }
}
```

After "Format Document":

``` r
function() {
    field <-
        if (missing(fields)) {
        function(x) TRUE;
    } else {
        function(x) x %in% fields
    }
}
```

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
#2467 Formatting: if-expression on newline after <- is indented wrong 
#2641 Indentation messed up for incomplete expressions 
#2659 Smart indent is set incorrectly when line ends with space
#2596 First time intellisense is slow

- Added analysis of incomplete expressions to formatter and smart indenter to help with indent calculation in multiline expressions.
- Track indent level based on the line that contains keyword that defines scope. Align content and the closing brace accordingly.
- Move some of the formatter code to helper classes
- Move package index building to broker connected since there is no R when package starts

- Derive interactive window mock from ToolPane (otherwise code throws in tests)
- Fix completion tests that now need explicit info fetching for function description

### CODE REVIEW

File: src/Languages/Core/Impl/Formatting/IndentBuilder.cs [hunk 1]
```diff
@@ -233,5 +233,17 @@ public IndentBuilder(IndentType indentType, int indentSize, int tabSize)
 
             return indent;
         }
+
+        /// <summary>
+        /// Determines indentation based on the leading whitespace in the current line.
+        /// </summary>
+        public static int GetLineIndentSize(TextBuilder tb, int position, int tabSize) {
```
Comment (int19h) [inline src/Languages/Core/Impl/Formatting/IndentBuilder.cs]: This should probably check `position` for validity, and assert or throw if it's 0.

Comment (int19h) [inline src/Languages/Core/Impl/Formatting/IndentBuilder.cs]: But you subtract 1 from it below. What happens if the result is -1, and that is passed to the indexer?

Comment (MikhailArkhipov) [inline src/Languages/Core/Impl/Formatting/IndentBuilder.cs]: `i >= 0` should bypass the loop?

Comment (int19h) [inline src/Languages/Core/Impl/Formatting/IndentBuilder.cs]: Ahh, subtle.

File: src/R/Editor/Impl/Completion/Providers/PackageFunctionCompletionProvider.cs [hunk 2]
```diff
@@ -153,19 +156,23 @@ public class PackageFunctionCompletionProvider : IRCompletionListProvider, IRHel
...
 
             IEnumerable<string> loadedPackages = _loadedPackagesProvider?.GetPackageNames() ?? Enumerable.Empty<string>();
             IEnumerable<string> filePackageNames = context.AstRoot.GetFilePackageNames();
             IEnumerable<string> allPackageNames = PackageIndex.PreloadedPackages.Union(filePackageNames).Union(loadedPackages);
 
-            return allPackageNames
-                .Select(packageName => GetPackageByName(packageName))
+            var list = new List<IPackageInfo>();
+            foreach (var name in allPackageNames) {
+                var info = await _packageIndex.GetPackageInfoAsync(name);
```
Comment (int19h) [inline src/R/Editor/Impl/Completion/Providers/PackageFunctionCompletionProvider.cs]: Does `GetPackageInfoAsync` do any R evals or anything else that requires a roundtrip to the host? If so, we might want to make it a batch API, so that it can do it for all these packages in one go, to avoid unnecessary latency on every request.

Comment (int19h) [inline src/R/Editor/Impl/Completion/Providers/PackageFunctionCompletionProvider.cs]: Can we then at least fire off all the async requests at once, and `WaitAll` a combination of them, so that throughput is maximized? It seems like in the worst case, this will produce a latency that is a multiple of the underling network latency by the number of packages fetched - meaning seconds of time, which would be very noticeable.

**Comment by MikhailArkhipov** [comment]
Made package fetching in batch. Generally it shouldn't be necessary since index is built and missing package means it was freshly installed or user mistyped its name so it is rarely more than one.

And fixed tests since some need function index pre-built and some were building it but didn't actually use it.

**Comment by int19h** [comment]
👍
