### PR TITLE
#2425, #2427 (autosaving and restoring session state)

### LINKED ISSUE #2425: Automatically save host state when connection to client is lost
Host process should be notified by the broker when the client has unexpectedly dropped connection for any reason, and should save its state to an Rdata file in a known location, to permit loading it in a new session.

### LINKED ISSUE #2427: Prompt to reload saved session state
Per #2425, host processes will save state on unexpected disconnects. When reconnecting, the user should get a prompt to reload the state if present.

### PR DESCRIPTION
**Pull request by int19h**
Resolve #2425: Automatically save host state when connection to client is lost
Resolve #2427: Prompt to reload saved session state

Disable reconnecting to live sessions.

When client disconnects from a websocket connection to broker, have broker disconnect from the host, so that the latter can shut down.

When shutting down host due to disconnect, save workspace image.

When starting a new session, check for autosaved workspace image, and prompt user to reload it.

When VS is closed, gracefully terminate any running hosts instead of just disconnecting from them.

When switching from one connection to another, gracefully terminate the old host once the switch is successful.

Expose session state in /sessions endpoint in the broker.

### CODE REVIEW

**Comment by int19h** [comment]
Requires https://github.com/Microsoft/R-Host/pull/93

File: src/Host/Client/Impl/Host/BrokerClient.cs [hunk 1]
```diff
@@ -89,7 +89,7 @@ internal abstract class BrokerClient : IBrokerClient {
             await TaskUtilities.SwitchToBackgroundThread();
 
             try {
-                bool sessionExists = await IsSessionRunningAsync(name, cancellationToken);
+                bool sessionExists = false; //await IsSessionRunningAsync(name, cancellationToken);
```
Comment (karthiknadig) [inline src/Host/Client/Impl/Host/BrokerClient.cs]: >//await IsSessionRunningAsync(name, cancellationToken); [](start = 44, length = 55)

Is this not needed?

File: src/Host/Client/Impl/rtvs/R/util.R [hunk 2]
```diff
@@ -241,4 +245,55 @@ fetch_file <- function(file_path) {
...
+	if (identical(res, 'YES')) {
+		# Use try instead of tryCatch, so that any errors are printed as usual.
+		loaded <- FALSE;
+		try({
+			load(autosave_filename, envir = .GlobalEnv);
+			loaded <- TRUE;
+		});
+
+		if (loaded) {
+			message(sprintf('Loaded workspace from autosaved image "%s".\n', autosave_filename));
```
Comment (karthiknadig) [inline src/Host/Client/Impl/rtvs/R/util.R]: >	 [](start = 1, length = 1)

tab to space

File: src/Host/Client/Impl/Host/BrokerClient.cs (hunk 1 above)
Comment (int19h) [inline src/Host/Client/Impl/Host/BrokerClient.cs]: Yes, that is the intent (since we decided to not go with reconnection in RTM). Comment is just so that it's readily obvious how to revert this later, when we get to it.

File: src/Host/Client/Impl/rtvs/R/util.R (hunk 2 above)
Comment (int19h) [inline src/Host/Client/Impl/rtvs/R/util.R]: Looks like we have a mix of tabs and spaces all over our .R files, and also different indentation levels. I'll go over and reformat them all.

File: src/Host/Client/Impl/Session/RSessionProvider.cs [hunk 3]
```diff
@@ -81,7 +82,14 @@ public class RSessionProvider : IRSessionProvider {
                 return;
             }
 
-            foreach (var session in _sessions.Values) {
+            var sessions = GetSessions();
+            var stopHostTasks = sessions.Select(session => session.StopHostAsync());
+            try {
+                Task.WhenAll(stopHostTasks).GetAwaiter().GetResult();
```
Comment (AlexanderSher) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: What is this change for?

File: src/Host/Broker/Impl/Sessions/Session.cs [hunk 4]
```diff
@@ -207,15 +208,23 @@ public class Session {
         }
 
         private async Task ClientToHostWorker(Stream stream, IMessagePipeEnd pipe) {
```
Comment (AlexanderSher) [inline src/Host/Broker/Impl/Sessions/Session.cs]: >ClientToHostWorker [](start = 27, length = 18)

`ClientToHostWorker` doesn't create a stream, so I don't think it should dispose it either

File: src/Host/Client/Impl/Session/RSessionProvider.cs (hunk 3 above)
Comment (int19h) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: To gracefully stop the hosts when we close VS, instead of merely disconnecting from them (disposing an `RHost` instance disconnects from the broker, but doesn't tell it to terminate the process).

Comment (AlexanderSher) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: In this case, shouldn't we schedule it to run in UI thread?

---
In reply to: [82472969](https://github.com/Microsoft/RTVS/pull/2465#discussion_r82472969) [](ancestors = 82472969)

**Comment by int19h** [comment]
Rebased and ready for merge - any additional feedback?

File: src/Host/Client/Impl/Session/RSessionProvider.cs (hunk 3 above)
Comment (AlexanderSher) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: In this case, shouldn't we schedule it to run in UI thread?

**Comment by MikhailArkhipov** [comment]
👍

File: src/Host/Client/Impl/Session/RSessionProvider.cs (hunk 3 above)
Comment (int19h) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: Would it make a difference? All it does is do a bunch of evals, mostly, which don't care which thread they're on. Or are you saying that VS will not actually wait for `Dispose` to complete?

Comment (int19h) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: If I understand correctly, the chain of `Dispose` calls that gets us here starts with the disposal of some MEF component - won't that necessarily be waited on by MEF?

Comment (int19h) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: I ran it under debugger, and `Dispose` is, in fact, called on UI thread when VS is closed.

Comment (AlexanderSher) [inline src/Host/Client/Impl/Session/RSessionProvider.cs]: MEF can call `Dispose` from any thread, but you're probably right that VS should wait until its MEF components are disposed.

**Comment by AlexanderSher** [comment]
👍
