### PR TITLE
Bug fixes

### LINKED ISSUE #2549: Canceling untrusted certificate connection throw unhandled exception
```
An unhandled exception of type 'System.Net.Http.HttpRequestException' occurred in mscorlib.dll
Additional information: An error occurred while sending the request.
```

### LINKED ISSUE #2607: Remove setting storage from package property page
We should be using `IWritableSettingsStorage` and only use Tools | Options page for editing

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
#2549 Canceling untrusted certificate connection throw unhandled exception 
 -  `HttpClient.GetAsync("/about", ...)` was not handling HTTP exceptions.

#2594 Occasionally there are multiple popups for certificate validation
 - remember outcome for certificate for the lifetime of the remote broker client

#2556 Occasional ObjectDisposedException on web socket
 - handle disposed exception on the socket since it can be disposed elsewhere

#2601 Sort out settings load on package initialize
- move setting loading off the package initialization path (we need to fix #2607 for real thing)

### CODE REVIEW

**Comment by huguesv** [comment]
Please check the host submodule, it looks like you may be reverting to an older commit there.

**Comment by MikhailArkhipov** [comment]
Sure. I thought I merged, but will double check

**Comment by MikhailArkhipov** [comment]
I don't see that PR is updating the submodule

**Comment by huguesv** [comment]
It looks different than it used to:
image

**Comment by MikhailArkhipov** [comment]
Looks like just because my R-Host was on 0.5, master decided that it likes 0.5 and not R-Host master

File: src/Package/Impl/Packages/R/RPackage.cs [hunk 1]
```diff
@@ -112,23 +112,27 @@ internal class RPackage : BasePackage<RLanguageService>, IRPackage {
             VsWpfOverrides.Apply();
             CranMirrorList.Download();
 
+            base.Initialize();
+
+            ProjectIconProvider.LoadProjectImages();
+            LogCleanup.DeleteLogsAsync(DiagnosticLogs.DaysToRetain);
+
+            IdleTimeAction.Create(CompleteInit, 20, this.GetType(), VsAppShell.Current);
```
Comment (AlexanderSher) [inline src/Package/Impl/Packages/R/RPackage.cs]: CPS requests package load:
```{csharp}
            await _threadHandling.SwitchToUIThread();
            // Make sure R package is loaded
            VsAppShell.EnsurePackageLoaded(RGuidList.RPackageGuid);

            // Verify project is not on a network share and give warning if it is
            CheckRemoteDrive(_projectDirectory);

            _workflow = _workflowProvider.GetOrCreate();
```
Does it still work with this change?

Comment (MikhailArkhipov) [inline src/Package/Impl/Packages/R/RPackage.cs]: The package will be loaded since initialization will be complete. But it depends what exactly project uses from the package. Appears to work in real life, but that's just one machine. I assume we are talking project reopen with workspace auto-load?

Comment (MikhailArkhipov) [inline src/Package/Impl/Packages/R/RPackage.cs]: (1) is basically add 

RPackage.LoadSettings

and call it from the project adter loading the package

**Comment by MikhailArkhipov** [comment]
Added IRPackage.LoadSettings and modified EnsurePackageLoaded

**Comment by AlexanderSher** [comment]
Ok, let's try it
👍
