### PR TITLE
Bug fixes

### LINKED ISSUE #3888: Pressing Esc in REPL doesn't clear commandline
This is in update 3.2. Looks like the fix to #3865 broke something else.

To repro: type anything in the REPL. Press Esc. What was typed remains there.

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
#3888 Pressing Esc in REPL doesn't clear commandline 
- Move 'CanInterrupt' to session extensions so it can be accessed from other places
- Move `IDebuggerModeTracker` down to Host.Client
- Fix `InterruptRCommand` accordingly

#3811 Live Markdown: R block does not execute if there are spaces between braces 
- Fix formatting so it does not format `{r` block in autoformat (call host to make sure range is formattable)

#3872 package::func() does not always bring signature help 
- Add async information fetching method to IFunctionIndex
- make sure function index data gets updated
- Add test

#3831 Unable to connect to Linux box 
- Simplify cert verification code, make sure we only return `false` when appropriate

Also:
- Add additional tests for `{r` block extraction
- In markdown R code formatting correct calculation of the formattable range

### CODE REVIEW

File: src/Host/Client/Impl/Debugging/IDebuggerModeTracker.cs [hunk 1]
```diff
@@ -3,7 +3,7 @@
 
 using System;
 
-namespace Microsoft.R.Components.InteractiveWorkflow {
+namespace Microsoft.R.Host.Client.Debugging {
```
Comment (AlexanderSher) [inline src/Host/Client/Impl/Debugging/IDebuggerModeTracker.cs]: I'd rather define `CanInterrupt` in `Components` assembly and make it extension to `IDebuggerModeTracker`.

Comment (MikhailArkhipov) [reply src/Host/Client/Impl/Debugging/IDebuggerModeTracker.cs]: But it is session we are interrupting. The fact that it checks the debugger state is implementation detail.

File: src/Windows/R/Editor/Impl/Completions/RCompletionSet.cs [hunk 2]
```diff
@@ -40,12 +40,48 @@ internal sealed class RCompletionSet : CompletionSet {
...
+            var matches = new Dictionary<int, List<Completion>>();
+            var maxKey = 0;
+
             var typedText = GetTypedText();
             if (typedText.Length == 0) {
                 return;
             }
 
-            _completions.ForEach(x => ((RCompletion)x).IsVisible = x.DisplayText.StartsWithIgnoreCase(typedText));
+            foreach (var c in _completions) {
```
Comment (MikhailArkhipov) [inline src/Windows/R/Editor/Impl/Completions/RCompletionSet.cs]: Restore original code. 15.3 fix was too aggressive

File: src/Package/Impl/Repl/Commands/ReplCommandController.cs [hunk 3]
```diff
@@ -159,18 +159,17 @@ public class ReplCommandController : ViewController {
...
-                    return true;
-                }
-            } else {
+            if (controller.HasActiveCompletionSession || controller.HasActiveSignatureSession(TextView)) {
                 controller.DismissAllSessions();
                 return true;
             }
+
+            // If session is reading user input, do not terminate it
+            if (!Workflow.RSession.IsReadingUserInput && Workflow.RSession.CanInterrupt(Services)) {
```
Comment (AlexanderSher) [inline src/Package/Impl/Repl/Commands/ReplCommandController.cs]: `CanInterrupt` is checked in `InterruptRCommand` already. Why do we need to check it here as well?

File: src/R/Editor/Impl/Extensions/StringExtensions.cs [hunk 4]
```diff
@@ -16,5 +17,27 @@ public static class StringExtensions {
...
+            if (start < 0) {
+                return TextRange.FromBounds(0, 0);
+            }
+
+            var bc = new BraceCounter<char>('{', '}');
+            var end = start;
+            bc.CountBrace(text[end]);
+            while (bc.Count > 0 && end < text.Length - 1) {
+                end++;
+                bc.CountBrace(text[end]);
```
Comment (AlexanderSher) [inline src/R/Editor/Impl/Extensions/StringExtensions.cs]: Don't you need to re-instantiate `BraceCounter` in the loop?

File: src/Package/Impl/Repl/Commands/ReplCommandController.cs (hunk 3 above)
Comment (MikhailArkhipov) [reply src/Package/Impl/Repl/Commands/ReplCommandController.cs]: I guess we can try and post command anyway... Let me see.

File: src/R/Editor/Impl/Extensions/StringExtensions.cs (hunk 4 above)
Comment (MikhailArkhipov) [reply src/R/Editor/Impl/Extensions/StringExtensions.cs]: No, it counts braces in the loop (it is a stack effectively) `bc.Count == 0` when braces match.

Comment (AlexanderSher) [reply src/R/Editor/Impl/Extensions/StringExtensions.cs]: Ok, do you care about cases like `}{}`?

File: src/R/Editor/Impl/Completions/Providers/PackageFunctionCompletionProvider.cs [hunk 5]
```diff
@@ -45,9 +45,10 @@ public class PackageFunctionCompletionProvider : IRCompletionListProvider, IRHel
         public IReadOnlyCollection<ICompletionEntry> GetEntries(IRIntellisenseContext context) {
             var completions = new List<ICompletionEntry>();
             var infoSource = _snippetInformationSource?.InformationSource;
-            var packages = GetPackages(context);
+            var packages = GetPackages(context).ToList();
```
Comment (AlexanderSher) [inline src/R/Editor/Impl/Completions/Providers/PackageFunctionCompletionProvider.cs]: Can this method be called on UI thread?

File: src/R/Editor/Impl/Extensions/StringExtensions.cs (hunk 4 above)
Comment (MikhailArkhipov) [reply src/R/Editor/Impl/Extensions/StringExtensions.cs]: Not really. It is up to the caller. The code will detect `{}`

File: src/Package/Impl/Repl/Commands/ReplCommandController.cs (hunk 3 above)
Comment (MikhailArkhipov) [reply src/Package/Impl/Repl/Commands/ReplCommandController.cs]: OK, simplified it back

File: src/R/Editor/Impl/Completions/Providers/PackageFunctionCompletionProvider.cs (hunk 5 above)
Comment (MikhailArkhipov) [reply src/R/Editor/Impl/Completions/Providers/PackageFunctionCompletionProvider.cs]: It is actually only called on UI thread

File: src/Windows/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflow.cs [hunk 6]
```diff
@@ -72,16 +68,16 @@ public sealed class RInteractiveWorkflow : IRInteractiveWorkflowVisual {
             History = historyProvider.CreateRHistory(this);
             Packages = packagesProvider.CreateRPackageManager(_settings, this);
             Plots = plotsProvider.CreatePlotManager(_settings, this, coreShell.FileSystem());
-            _operations = new RInteractiveWorkflowOperations(this, _debuggerModeTracker, Shell);
+            _operations = new RInteractiveWorkflowOperations(this, debuggerModeTracker, Shell);
 
-            _activeTextViewTracker.LastActiveTextViewChanged += LastActiveTextViewChanged;
+            activeTextViewTracker1.LastActiveTextViewChanged += LastActiveTextViewChanged;
```
Comment (AlexanderSher) [inline src/Windows/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflow.cs]: Why do you need another variable instead of `activeTextViewTracker`?

File: src/R/Editor/Impl/Completions/Providers/PackageFunctionCompletionProvider.cs (hunk 5 above)
Comment (AlexanderSher) [reply src/R/Editor/Impl/Completions/Providers/PackageFunctionCompletionProvider.cs]: Then you may want to use `ITaskService.Wait` for the `GetAllFilePackagesAsync`. That will prevent UI from freezing

Comment (AlexanderSher) [reply src/R/Editor/Impl/Completions/Providers/PackageFunctionCompletionProvider.cs]: It returns `false` if we stopped waiting by timeout.

File: src/Package/Impl/Repl/Commands/ReplCommandController.cs [hunk 7]
```diff
@@ -14,6 +13,7 @@
 using Microsoft.R.Editor.Completions;
 using Microsoft.R.Editor.Document;
 using Microsoft.R.Editor.Formatting;
+using Microsoft.R.Host.Client.Session;
```
Comment (AlexanderSher) [inline src/Package/Impl/Repl/Commands/ReplCommandController.cs]: Probably not needed anymore

File: src/Package/Impl/Repl/VsRInteractiveWorkflowProvider.cs [hunk 8]
```diff
@@ -12,6 +12,7 @@
 using Microsoft.R.Components.InteractiveWorkflow.Implementation;
 using Microsoft.R.Components.PackageManager;
 using Microsoft.R.Components.Plots;
+using Microsoft.R.Host.Client.Debugging;
```
Comment (AlexanderSher) [inline src/Package/Impl/Repl/VsRInteractiveWorkflowProvider.cs]: Same here

File: src/Windows/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflow.cs (hunk 6 above)
Comment (MikhailArkhipov) [reply src/Windows/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveWorkflow.cs]: Resharper change lol

File: src/Host/Client/Impl/Microsoft.R.Host.Client.csproj [hunk 9]
```diff
@@ -13,7 +13,7 @@
   <ItemGroup>
     <PackageReference Include="MicroBuild.Core" Version="0.2.0" />
     <PackageReference Include="Microsoft.AspNetCore.WebSockets.Protocol" Version="0.1.0" />
-    <PackageReference Include="System.Net.Http.WinHttpHandler" Version="4.3.0" />
+    <PackageReference Include="System.Net.Http.WinHttpHandler" Version="4.4.0" />
```
Comment (AlexanderSher) [inline src/Host/Client/Impl/Microsoft.R.Host.Client.csproj]: I had type resolution problems because of this change. Do you need it?

Comment (MikhailArkhipov) [reply src/Host/Client/Impl/Microsoft.R.Host.Client.csproj]: Not really. Seems to work, but I can roll back if you had issues.

**Comment by AlexanderSher** [comment]
👍
