### PR TITLE
Menu, version and message box positioning fixes

### LINKED ISSUE #3022: Incorrect wording (or version comparison) with remote machine
image

Should say 0.6 is LOWER than 1.0

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
#3022 Incorrect wording (or version comparison) with remote machine 
- use Version to compare rather than compare by fields

#3025 Saying NO when prompted to install R client should mean NO 
- fix incorrect comparison

#3034 Microsoft R client detection does not work 
- removed 'Switch to MRC' command since we support multiple Rs and there is MRO, MRO from SQL, etc

#3023 Certificate warning dialog always appears on primary monitor 
 - position message box properly and above the progress dialog

#3036 Remove 'Check for updates' from VS 2017 
 - removed check for updates and survey/news. In VS 2017+ we should be getting VS notifications and should join start page feed for news.

### CODE REVIEW

File: src/Common/Core/Impl/OS/Win32MessageBox.cs [hunk 1]
```diff
@@ -72,8 +73,48 @@ public enum Result : uint {
...
+                return (Result)NativeMethods.MessageBox(form.Handle, message, Resources.MessageBoxTitle, (uint)flags);
             }
         }
+
+        private static Task MoveMessageBoxAsync(string title, int centerX, int centerY) {
+            return Task.Run(() => {
+                IntPtr msgBoxHandle = IntPtr.Zero;
+                var startTime = DateTime.Now;
+
+                while (msgBoxHandle == IntPtr.Zero && (DateTime.Now - startTime).TotalMilliseconds < 2000) {
```
Comment (AlexanderSher) [inline src/Common/Core/Impl/OS/Win32MessageBox.cs]: What is this for?

Comment (MikhailArkhipov) [inline src/Common/Core/Impl/OS/Win32MessageBox.cs]: It is trying to locate message box handle. This task starts BEFORE the message box is shown so it can'd find the handle right away.
