### PR TITLE
Fixes issue where broker user cannot kill process running as another user.

### LINKED ISSUE #3600: Linux: RHost process does not get killed after disconnect

### PR DESCRIPTION
**Pull request by karthiknadig**
fixes #3600

### CODE REVIEW

File: src/Linux/Core/Impl/OS/UnixProcessServices.cs [hunk 1]
```diff
@@ -20,5 +20,12 @@ public class UnixProcessServices : IProcessServices {
         public Process Start(string path) {
             return Process.Start(path);
         }
+
+        // usage:
+        // Microsoft.R.Host.RunAsUser [-q]
+        //    -q: Quiet
+        //    -k <pid> : kill process
+        private const string runAsUserPath = "/usr/lib/rtvs/Microsoft.R.Host.RunAsUser";
```
Comment (int19h) [inline src/Linux/Core/Impl/OS/UnixProcessServices.cs]: Why not just `public const`?

File: src/Linux/Core/Impl/OS/UnixProcess.cs [hunk 2]
```diff
@@ -36,9 +35,17 @@ public class UnixProcess : IProcess {
...
         public void Kill() {
-            _process.Kill();
+            // This is needed because broker user cannot kill process running as another user.
+            KillProcess(_ps, _process.Id);
+        }
+
+        private static void KillProcess(IProcessServices ps, int pid) {
+            ProcessStartInfo psi = new ProcessStartInfo();
+            psi.FileName = UnixProcessServices.RunAsUserBinPath;
+            psi.Arguments = "-k {pid}";
```
Comment (int19h) [inline src/Linux/Core/Impl/OS/UnixProcess.cs]: It sounds like it could use RAU to run `kill -9 <pid>`?

Comment (karthiknadig) [inline src/Linux/Core/Impl/OS/UnixProcess.cs]: It could. Is there any reason it should not call `kill(3)`?

Comment (int19h) [inline src/Linux/Core/Impl/OS/UnixProcess.cs]: What I meant is that then we won't need the `-k` switch at all, so RAU code remains single-purpose (launching elevated processes).

Comment (karthiknadig) [inline src/Linux/Core/Impl/OS/UnixProcess.cs]: Ahh! Got it. I will update this.

**Comment by karthiknadig** [comment]
ping

File: src/Linux/Core/Impl/OS/UnixProcess.cs [hunk 3]
```diff
@@ -36,9 +38,22 @@ public class UnixProcess : IProcess {
...
 
-
         public void Kill() {
-            _process.Kill();
+            // This is needed because broker user cannot kill process running as another user.
+            KillProcess(_ps, _process.Id);
+        }
+
+        private static void KillProcess(IProcessServices ps, int pid) {
+            KillProcessMessage kpm = new KillProcessMessage() { ProcessId = pid };
```
Comment (MikhailArkhipov) [inline src/Linux/Core/Impl/OS/UnixProcess.cs]: You may want to try-catch IOException here

File: src/Linux/Native/RunAsUser/src/main.cpp [hunk 4]
```diff
@@ -294,13 +297,15 @@ int run_rhost(const picojson::object& json, const char* user, const gid_t gid, c
             if (err) {
                 logf(log_verbosity::minimal, "Error rhost exited:[%d] %s\n", err, strerror(err));
             } else {
-                logf(log_verbosity::minimal, "RHost exited.\n");
+                logf(log_verbosity::minimal, "RHost exited normally.\n");
             }
         } else if (WIFSIGNALED(ws)) {
             logf(log_verbosity::minimal, "Error rhost terminated by a signal: %d\n", WTERMSIG(ws));
```
Comment (MikhailArkhipov) [inline src/Linux/Native/RunAsUser/src/main.cpp]: Not related to this change, but in log messages accessible to the user I'd put `Microsoft.R.Host.exe` rather than `rhost` since no one out there knows what `rhost` means

File: src/Linux/Native/RunAsUser/src/main.cpp [hunk 5]
```diff
@@ -475,7 +480,60 @@ int authenticate_and_run(const picojson::object& json) {
...
+    int err = 0;
+    char** args = calloc_or_exit<char**>(4, sizeof(char*));
+    std::string arg1("-9"); // SIGKILL
+    char carg2[100] = {}; // pid
+    sprintf(carg2, "%d", pid);
+    std::string arg2(carg2); // SIGKILL
+
+    std::string kill_path(RTVS_KILL_PATH);
+    args[0] = calloc_or_exit<char*>(kill_path.size() + 1, sizeof(char));
+    memcpy(args[0], kill_path.c_str(), kill_path.size());
```
Comment (MikhailArkhipov) [inline src/Linux/Native/RunAsUser/src/main.cpp]: no strdup equivalent?

File: src/Linux/Native/RunAsUser/src/main.cpp [hunk 6]
```diff
@@ -475,7 +480,60 @@ int authenticate_and_run(const picojson::object& json) {
...
+    memcpy(args[2], arg2.c_str(), arg2.size());
+
+    args[3] = NULL;
+
+    int pid = fork();
+    if (pid == -1) {
+        err = errno;
+        logf(log_verbosity::minimal, "Error [fork]: %s\n", explain_errno_fork(err));
+        return err;
+    } else if (pid == 0) {
```
Comment (MikhailArkhipov) [inline src/Linux/Native/RunAsUser/src/main.cpp]: `else` is unnecessary

File: src/Linux/Native/RunAsUser/src/main.cpp [hunk 7]
```diff
@@ -475,7 +480,60 @@ int authenticate_and_run(const picojson::object& json) {
...
+            logf(log_verbosity::minimal, "Error kill terminated by a signal: %d\n", WTERMSIG(ws));
+            err = ws;
+        }
+    }
+
+    return err;
+}
 int main(int argc, char **argv) {
     int option = 0;
     bool quiet = false;
```
Comment (MikhailArkhipov) [inline src/Linux/Native/RunAsUser/src/main.cpp]: just `quiet = option == 'q'` ?

File: src/Linux/Native/RunAsUser/src/main.cpp (hunk 5 above)
Comment (karthiknadig) [inline src/Linux/Native/RunAsUser/src/main.cpp]: Will try with `strdup`. I think it should work.

File: src/Linux/Core/Impl/OS/UnixProcessServices.cs [hunk 8]
```diff
@@ -20,5 +20,21 @@ public class UnixProcessServices : IProcessServices {
         public Process Start(string path) {
             return Process.Start(path);
         }
+
+        // usage:
+        // Microsoft.R.Host.RunAsUser [-q]
+        //    -q: Quiet
+        private const string RunAsUserBinPath = "/usr/lib/rtvs/Microsoft.R.Host.RunAsUser";
+
+        public static Process CreateRunAsUserProcess(IProcessServices ps, bool quietMode) {
```
Comment (AlexanderSher) [inline src/Linux/Core/Impl/OS/UnixProcessServices.cs]: Why is it static?

File: src/Linux/Core/Impl/OS/UnixProcessServices.cs [hunk 9]
```diff
@@ -20,5 +20,21 @@ public class UnixProcessServices : IProcessServices {
         public Process Start(string path) {
             return Process.Start(path);
         }
+
+        // usage:
+        // Microsoft.R.Host.RunAsUser [-q]
+        //    -q: Quiet
+        private const string RunAsUserBinPath = "/usr/lib/rtvs/Microsoft.R.Host.RunAsUser";
```
Comment (AlexanderSher) [inline src/Linux/Core/Impl/OS/UnixProcessServices.cs]: Can this path be used with other processes?

Comment (karthiknadig) [inline src/Linux/Core/Impl/OS/UnixProcessServices.cs]: This path has meaning only to broker and not other processes.

Comment (AlexanderSher) [inline src/Linux/Core/Impl/OS/UnixProcessServices.cs]: Then we should move it back to the Linux Broker assembly.

File: src/Linux/Native/RunAsUser/src/main.cpp [hunk 10]
```diff
@@ -49,8 +50,10 @@ static constexpr char RTVS_RESPONSE_TYPE_RTVS_ERROR[] = "rtvs-error";
 
 static constexpr char RTVS_MSG_AUTH_ONLY[] = "AuthOnly";
 static constexpr char RTVS_MSG_AUTH_AND_RUN[] = "AuthAndRun";
+static constexpr char RTVS_MSG_KILL_PROCESS[] = "KillProcess";
 
 static constexpr char RTVS_RHOST_PATH[] = "/usr/lib/rtvs/Microsoft.R.Host";
+static constexpr char RTVS_KILL_PATH[] = "/bin/kill";
```
Comment (int19h) [inline src/Linux/Native/RunAsUser/src/main.cpp]: Sorry, I should have clarified what I meant here.

If we pass the binary as an argument in the JSON message, instead of hardcoding, then this thing doesn't need to know what it is starting. And then you can pass the host binary or kill or whatever from the managed side, and there's no special code for kill.

(And if this doesn't work for some reason, then there's no point using kill as a process instead of the corresponding API.)

Comment (karthiknadig) [inline src/Linux/Native/RunAsUser/src/main.cpp]: That was intentional. I wanted to restrict it to specific processes that we use, rather than make it general purpose.

Comment (int19h) [inline src/Linux/Native/RunAsUser/src/main.cpp]: It feels like it would be better as a more generic API, so that the broker can use it more flexibly as and when it needs to. What's the downside? If it's mainly security, then, given that the host can run arbitrary code (including spawning arbitrary child processes), I think it's moot anyway.

Comment (karthiknadig) [inline src/Linux/Native/RunAsUser/src/main.cpp]: I had Created https://github.com/Microsoft/RTVS/issues/3702 to track that.
