### PR TITLE
Two bug fixes

### LINKED ISSUE #3953: Exception in run loop, close VS while running shiny app.
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Exception in RHost run loop:
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.get_Token()
   at Microsoft.Common.Core.Disposables.DisposeToken.get_CancellationToken()
   at Microsoft.R.Components.InteractiveWorkflow.Implementation.InteractiveWindowConsole.<WriteAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Common.Core.TaskExtensions.ReThrowTaskException(Object state)
   at Microsoft.Common.Core.TaskExtensions.DoNotWait(Task task)
   at Microsoft.R.Components.InteractiveWorkflow.Implementation.InteractiveWindowConsole.WriteError(String text)
   at Microsoft.R.Components.InteractiveWorkflow.Implementation.InteractiveWindowConsole.WriteErrorLine(String text)
   at Microsoft.R.Components.InteractiveWorkflow.Impl......
<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

### LINKED ISSUE #4002: Start Container always activates output window
Takes away REPL. Should only activate on error OR has an option similar to VS Build has ('always open Error list...')

### PR DESCRIPTION
**Pull request by AlexanderSher**
- Fix #3953: Exception in run loop, close VS while running shiny app.
- Fix #4002: Start Container always activates output window

### CODE REVIEW

File: src/Containers/Impl/Docker/LocalDockerService.cs [hunk 1]
```diff
@@ -199,15 +199,15 @@ public Task<string> RepositoryLogoutAsync(RepositoryCredentials auth, Cancellati
...
+                    Output.WriteError(Invariant($"{outputPrefix}> ERROR: {Resources.LocalDockerOutputStreamException}"));
                 }
                 throw new ContainerException(Resources.LocalDockerOutputStreamException);
             } catch(OperationCanceledException) when (!failOnTimeout && !ct.IsCancellationRequested){
             }
 
             var error = await process.StandardError.ReadToEndAsync();
             if (!string.IsNullOrEmpty(error) && !IsSecurityWarning(error)) {
-                Output.Write(Invariant($"{outputPrefix}> ERROR: {error}"));
+                Output.WriteError(Invariant($"{outputPrefix}> ERROR: {error}"));
```
Comment (MikhailArkhipov) [inline src/Containers/Impl/Docker/LocalDockerService.cs]: `ERROR` might need to be localized

**Comment by MikhailArkhipov** [comment]
👍
