### PR TITLE
UI fixes

### LINKED ISSUE #4110: Container window message may benefit from some margins
Text is a bit too close to right/left edges

image

### LINKED ISSUE #4111: Container window UI adjustments
- From containers window, have a link to bring up the dockerfile template in an editor
so that people dont have to hunt it down.  

a. usable for pointing the dockerhub url base image
b. usable for adding default pkgs
c. usable for a link to our docs

Also
- Link back to Workspaces and we have with Containers... there
- Some sort of indication that Create is clickable?
- Double click on container connects to it if it is running? Not sure if it is feasible though.

See also #4110

### PR DESCRIPTION
**Pull request by AlexanderSher**
- Fix #4110: Container window message may benefit from some margins
- Fix #4111: Container window UI adjustment

### CODE REVIEW

File: src/R/Components/Impl/Containers/Implementation/ContainerManager.cs [hunk 1]
```diff
@@ -88,16 +90,37 @@ internal class ContainerManager : IContainerManager {
...
+            return CreateLocalDockerFromContentAsync(dockerImageContent, name, version, port, cancellationToken);
+        }
+
+        public async Task<IContainer> CreateLocalDockerFromFileAsync(string name, string filePath, int port, CancellationToken cancellationToken = default(CancellationToken)) {
+            var dockerImageContent = await LoadDockerImageContent(filePath, cancellationToken);
+            return await CreateLocalDockerFromContentAsync(dockerImageContent, name, LatestVersion, port, cancellationToken);
+        }
+
+        private static async Task<string> LoadDockerImageContent(string filePath, CancellationToken cancellationToken) {
+            using (var client = new HttpClient()) {
```
Comment (MikhailArkhipov) [inline src/R/Components/Impl/Containers/Implementation/ContainerManager.cs]: Do we handle HttpException etc somewhere?

**Comment by MikhailArkhipov** [comment]
Hard to see without screenshot  :-) Make sure we don't crash if network is down. 👍

**Comment by AlexanderSher** [comment]
Ok, let me add couple more exception handlers
