### PR TITLE
Container manager bug fixes

### LINKED ISSUE #3939: Save credentials for created local docker container

### PR DESCRIPTION
**Pull request by AlexanderSher**
#3939: Save credentials for created local docker container
#3952: Container password field should show system password character
#3963: Delete should be disabled for running containers (it actually shows the popup)
#3964: Connection is not removed after the container is deleted
#3967: Use docker file hash as the image name
#3976: Container dialog 'Version' field should have tooltip/watermark with explanation
#3978: UI issues in Create Container panel
#3980: Show watermark on Containers window instead of UI that docker isn't installed

### CODE REVIEW

File: src/Windows/Core/Impl/Security/SecurityService.cs [hunk 1]
```diff
@@ -60,23 +61,38 @@ public class SecurityService : ISecurityService {
...
-        private Credentials ReadSavedCredentials(string authority) {
-            using (var ch = CredentialHandle.ReadFromCredentialManager(authority)) {
-                if (ch != null) {
-                    var credData = ch.GetCredentialData();
-                    return Credentials.Create(credData.UserName, SecurityUtilities.SecureStringFromNativeBuffer(credData.CredentialBlob));
+        public void SaveUserCredentials(string authority, string userName, SecureString password, bool save) {
+            var creds = default(NativeMethods.CredentialData);
+            try {
+                creds.TargetName = authority;
+                // We have to save the credentials even if user selected NOT to save. Otherwise, user will be asked to enter
```
Comment (MikhailArkhipov) [inline src/Windows/Core/Impl/Security/SecurityService.cs]: This sounds insecure. Why are we not respecting user's intent not to save? Perhaps they want to put container somewhere or have encrypted disk and want data to be secure. This may not pass sec review.

Comment (AlexanderSher) [reply src/Windows/Core/Impl/Security/SecurityService.cs]: This isn't related to the container. These credentials are used by connection to that container and aren't stored in the container itself. The same logic is used when we connect to any broker using URL.

File: src/Windows/R/Components/Impl/Resources.resx [hunk 2]
```diff
@@ -442,12 +442,18 @@ If you want to delete all data on the remote machine you must delete your user p
   <data name="ConnectionManager_RemoveConnectionConfirmation" xml:space="preserve">
     <value>Are you sure you want to remove the '{0}' connection?</value>
   </data>
+  <data name="ContainerManager_ContainerServiceIsNotInstalled" xml:space="preserve">
+    <value>Docker service isn't installed.\nTo start working with containers, install Docker for Windows and restart VS.</value>
+  </data>
+  <data name="ContainerManager_ContainerServiceIsNotRunning" xml:space="preserve">
+    <value>Docker service isn't running.\nTo start working with containers, run Docker for Windows and restart VS.</value>
```
Comment (MikhailArkhipov) [inline src/Windows/R/Components/Impl/Resources.resx]: Restart Visual Studio

File: src/Windows/R/Components/Impl/Resources.resx [hunk 3]
```diff
@@ -442,12 +442,18 @@ If you want to delete all data on the remote machine you must delete your user p
   <data name="ConnectionManager_RemoveConnectionConfirmation" xml:space="preserve">
     <value>Are you sure you want to remove the '{0}' connection?</value>
   </data>
+  <data name="ContainerManager_ContainerServiceIsNotInstalled" xml:space="preserve">
+    <value>Docker service isn't installed.\nTo start working with containers, install Docker for Windows and restart VS.</value>
```
Comment (MikhailArkhipov) [inline src/Windows/R/Components/Impl/Resources.resx]: We usually auto-open the download page. `ProcessServices.Start('https://www.docker.com/docker-windows')`

Comment (MikhailArkhipov) [inline src/Windows/R/Components/Impl/Resources.resx]: Does `\n` actually work here? since it is `xml:space="preserve"` it should be just regular formatting

File: src/Windows/Core/Impl/Security/SecurityService.cs (hunk 1 above)
Comment (MikhailArkhipov) [reply src/Windows/Core/Impl/Security/SecurityService.cs]: But then it is even less secure. We allow reconnection without re-entering creds?

File: src/Windows/R/Components/Impl/Resources.resx (hunk 3 above)
Comment (AlexanderSher) [reply src/Windows/R/Components/Impl/Resources.resx]: Do we want to open it every time user clicks on the "Containers" button?

Comment (AlexanderSher) [reply src/Windows/R/Components/Impl/Resources.resx]: Good catch.

Comment (MikhailArkhipov) [reply src/Windows/R/Components/Impl/Resources.resx]: Only after reporting the error. Same as in say, markdown publishing and pandoc

File: src/Windows/Core/Impl/Security/SecurityService.cs (hunk 1 above)
Comment (AlexanderSher) [reply src/Windows/Core/Impl/Security/SecurityService.cs]: https://msdn.microsoft.com/en-us/library/windows/desktop/aa374788(v=vs.85).aspx


Value | Meaning
-- | --
CRED_PERSIST_SESSION 1 (0x1) | The credential persists for the life of the logon session.  It will not be visible to other logon sessions of this same user. It  will not exist after this user logs off and back on.
CRED_PERSIST_LOCAL_MACHINE 2 (0x2) | The credential persists for all subsequent logon sessions on this  same computer. It is visible to other logon sessions of this same user  on this same computer and not visible to logon sessions for this user on  other computers. Windows Vista Home Basic, Windows Vista Home Premium, Windows Vista Starter and Windows XP Home Edition:  This value is not supported.
CRED_PERSIST_ENTERPRISE 3 (0x3) | The credential persists for all subsequent logon sessions on this  same computer. It is visible to other logon sessions of this same user  on this same computer and to logon sessions for this user on other  computers. This option can be implemented as locally persisted credential if the  administrator or user configures the user account to not have roam-able  state. For instance, if the user has no roaming profile, the credential  will only persist locally. Windows Vista Home Basic, Windows Vista Home Premium, Windows Vista Starter and Windows XP Home Edition:  This value is not supported.

Since we save it for CRED_PERSIST_SESSION, user won't be able to reuse these credentials from other sessions.

Comment (MikhailArkhipov) [reply src/Windows/Core/Impl/Security/SecurityService.cs]: OK, Need to study it more though...

**Comment by MikhailArkhipov** [comment]
👍

File: src/Windows/R/Components/Impl/Resources.resx (hunk 3 above)
Comment (AlexanderSher) [reply src/Windows/R/Components/Impl/Resources.resx]: Error is reported in the watermark. I can add a clickable link to the message. Will that work?

Comment (MikhailArkhipov) [reply src/Windows/R/Components/Impl/Resources.resx]: Sure

File: src/Windows/Core/Impl/Security/SecurityService.cs (hunk 1 above)
Comment (karthiknadig) [reply src/Windows/Core/Impl/Security/SecurityService.cs]: The case were this is iffy, is when the user says they don't want to save the creds. The problem is if we don't save it (temporarily) any connection attempt will request user to enter credentials. if the save is disabled, you will see credentials prompt show to you at least 4 times (Test connection, repl connection, intellisense, etc), before the connection is ready. Any call to broker (except About and info), will require the credentials and credential window will be presented. The iffy part is when this information is removed. Currently it is removed when user logs-out of windows . But we could remove it on connection switch, if the save flag is not set. But that will be an explicit remove.
