### PR TITLE
Fixes NRE in Broker SessionManager.GetSessions

### LINKED ISSUE #2684: NRE in Broker SessionManager.GetSessions(IIdentity)
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL09L5LQJUEQ": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.R.Host.Broker.Sessions.SessionManager.GetSessions(IIdentity user)
   at Microsoft.R.Host.Broker.Sessions.SessionsController.GetAsync()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

### PR DESCRIPTION
**Pull request by karthiknadig**
Fixes #2684

### CODE REVIEW

File: src/Host/Broker/Impl/Sessions/SessionManager.cs [hunk 1]
```diff
@@ -51,7 +51,7 @@ ILogger<Process> hostOutputLogger
             lock (_sessions) {
                 List<Session> userSessions;
                 _sessions.TryGetValue(user.Name, out userSessions);
-                return userSessions.ToArray() ?? Enumerable.Empty<Session>();
+                return userSessions?.ToArray() ?? Enumerable.Empty<Session>();
```
Comment (AlexanderSher) [inline src/Host/Broker/Impl/Sessions/SessionManager.cs]: return _sessions.TryGetValue(user.Name, out userSessions) ? userSessions.ToArray() : Enumerable.Empty<Session>()

Comment (karthiknadig) [inline src/Host/Broker/Impl/Sessions/SessionManager.cs]: That was a bit hard to read. However, I will change it to more verbose form:
```
                if(_sessions.TryGetValue(user.Name, out userSessions)) {
                    return userSessions.ToArray();
                }
                return Enumerable.Empty<Session>();
```

**Comment by AlexanderSher** [comment]
👍
