### PR TITLE
Package Manager VM Fixes

### LINKED ISSUE #1450: Update package crashes
Trying to get call stack

### LINKED ISSUE #1454: Uninstall package crashes
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException
   at System.ThrowHelper.ThrowNotSupportedException(System.ExceptionResource)
   at System.Collections.ObjectModel.ReadOnlyCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].System.Collections.Generic.IList<T>.RemoveAt(Int32)
   at Microsoft.Common.Core.Collections.ListExtensions.RemoveWhere[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IList`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>)
   at Microsoft.R.Components.PackageManager.Implementation.ViewModel.RPackageManagerViewModel+<UninstallAsync>d__35.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Common.Core.TaskExtensions+<DoNotWait>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

### LINKED ISSUE #1456: Package manager loaded view doesn't refresh when session is mutated or reset

### LINKED ISSUE #1459: 'Sources' button on package manager does nothing
We should either wire it to RTools | Options or hide it. (The cogwhell)

### LINKED ISSUE #1460: pk mgr: search currently search at beginning of name
it should search anywhere in the name.  ie:

cox 

should find: 

aCoxb

### LINKED ISSUE #1463: Package manager detail view should have margin at bottom
It would look better with some padding there, right now it's only a couple of pixels next to bottom.

image

### PR DESCRIPTION
**Pull request by AlexanderSher**
- Add Load/Unload/Update methods to RPackageManagerViewModel
- Make IPackageManager.InstallPackage / IPackageManager.UninstallPackage / IPackageManager.LoadPackage / IPackageManager.UnloadPackage async. Missing input in REPL will be fixed later: #1469
- Make InstallAsync/UninstallAsync refresh installed packages cause existing logic skips dependent packages
- Fix #1450: Update package crashes
- Fix #1454: Uninstall package crashes
- Fix #1456: Package manager loaded view doesn't refresh when session is mutated or reset
- Fix #1459: 'Sources' button on package manager does nothing
- Fix #1460: pk mgr: search currently search at beginning of name
- Fix #1463: Package manager detail view should have margin at bottom

### CODE REVIEW

File: src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs [hunk 1]
```diff
@@ -76,44 +76,74 @@ internal class RPackageManager : IRPackageManager {
...
+            try {
+                using (var request = await _interactiveWorkflow.RSession.BeginInteractionAsync()) {
+                    if (string.IsNullOrEmpty(libraryPath)) {
+                        await request.InstallPackage(name);
+                    } else {
+                        await request.InstallPackage(name, libraryPath);
+                    }
+                }
+            }
+            catch (MessageTransportException ex) {
```
Comment (MikhailArkhipov) [inline src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs]: CanceledException?

File: src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs [hunk 2]
```diff
@@ -77,11 +77,46 @@ public static class RSessionEvaluationCommands {
...
+            var script = $"install.packages({name.ToRStringLiteral()}, lib={libraryPath.ToRPath().ToRStringLiteral()})\n";
+            return interaction.RespondAsync(script);
+        }
+        
+        public static Task UninstallPackage(this IRSessionInteraction interaction, string name) {
+            var script = $"remove.packages({name.ToRStringLiteral()})\n";
+            return interaction.RespondAsync(script);
+        }
+
+        public static Task UninstallPackage(this IRSessionInteraction interaction, string name, string libraryPath) {
```
Comment (MikhailArkhipov) [inline src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs]: Maybe just one method with optional libraryPath? It would make code below shorter with fewer ifs

File: src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs [hunk 3]
```diff
@@ -76,44 +76,74 @@ internal class RPackageManager : IRPackageManager {
...
-                script = string.Format("remove.packages({0}, lib={1})", name.ToRStringLiteral(), libraryPath.ToRPath().ToRStringLiteral());
+        public async Task UninstallPackage(string name, string libraryPath) {
+            if (!_interactiveWorkflow.RSession.IsHostRunning) {
+                throw new RPackageManagerException(Resources.PackageManager_EvalSessionNotAvailable);
             }
 
-            _interactiveWorkflow.Operations.EnqueueExpression(script, true);
+            try {
+                using (var request = await _interactiveWorkflow.RSession.BeginInteractionAsync()) {
+                    if (string.IsNullOrEmpty(libraryPath)) {
```
Comment (MikhailArkhipov) [inline src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs]: Avoid ifs with optional libraryPath?

File: src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs (hunk 1 above)
Comment (AlexanderSher) [inline src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs]: `OperationCanceledException` propagated to the caller

**Comment by MikhailArkhipov** [comment]
:+1:

**Comment by int19h** [comment]
:+1:

File: src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs (hunk 3 above)
Comment (AlexanderSher) [inline src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs]: @huguesv, can we pass `null` the `lib` parameter?

**Comment by AlexanderSher** [comment]
Ok, I want @huguesv to take a look at the PR cause there are changes in his code

File: src/R/Components/Impl/PackageManager/IRPackageManager.cs [hunk 4]
```diff
@@ -69,36 +69,36 @@ public interface IRPackageManager : IDisposable {
         /// </summary>
         /// <param name="name">Package name.</param>
         /// <param name="libraryPath">
-        /// Optional library path (in any format). Pass null to use the default
-        /// for the session ie. the first one in .libPaths().
+        ///     Optional library path (in any format). Pass null to use the default
+        ///     for the session ie. the first one in .libPaths().
         /// </param>
-        void InstallPackage(string name, string libraryPath);
+        Task InstallPackage(string name, string libraryPath);
```
Comment (huguesv) [inline src/R/Components/Impl/PackageManager/IRPackageManager.cs]: Rename these to have Async suffix.

File: src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs [hunk 5]
```diff
@@ -77,11 +77,46 @@ public static class RSessionEvaluationCommands {
             return evaluation.EvaluateAsync(script, REvaluationKind.Json);
         }
 
+        public static Task InstallPackage(this IRSessionInteraction interaction, string name) {
```
Comment (huguesv) [inline src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs]: We have RSessionInteractionCommands.cs for extensions of IRSessionInteraction.  I know we have some more in this file that probably should have been moved already, but haven't.  Up to you.

File: src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs (hunk 3 above)
Comment (huguesv) [inline src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs]: It looks like we can:
```
> install.packages('dpa', lib=NULL)
Installing package into ‘C:/Users/huvalo/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)

```

File: src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs [hunk 6]
```diff
@@ -295,13 +375,44 @@ internal class RPackageManagerViewModel : BindableBase, IRPackageManagerViewMode
...
+                }
+
+                await UpdateLoadedPackages(currentInstalledPackages, loadedPackageNames);
+                _coreShell.DispatchOnUIThread(() => {
+                    if (_selectedTab == SelectedTab.LoadedPackages) {
+                        IsLoading = false;
+                        ReplaceItems(_loadedPackages);
+                    }
+                });
+            } catch (RPackageManagerException ex) {
```
Comment (huguesv) [inline src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs]: Do you need to catch OperationCanceledException here, or is it handled by a caller?

**Comment by huguesv** [comment]
:+1:

File: src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs (hunk 5 above)
Comment (AlexanderSher) [inline src/Host/Client/Impl/Session/RSessionEvaluationCommands.cs]: This class requires refactoring anyway. Let it be here for now

File: src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs (hunk 6 above)
Comment (AlexanderSher) [inline src/R/Components/Impl/PackageManager/Implementation/ViewModel/RPackageManagerViewModel.cs]: It is handled by `DoNotWait`

File: src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs (hunk 3 above)
Comment (AlexanderSher) [inline src/R/Components/Impl/PackageManager/Implementation/RPackageManager.cs]: I don't like it, better have couple of `if`s
