### PR TITLE
Fix #4032: ObjectDisposedException in WorkspaceVariableProvider provider

### LINKED ISSUE #4032: ObjectDisposedException in WorkspaceVariableProvider provider
From user logs on `1.2.30905.1244`
May need to check of session is gone

```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
   at Microsoft.Common.Core.Disposables.DisposableBag.ThrowIfDisposed()
   at Microsoft.VisualStudio.R.Package.Repl.VsRInteractiveWorkflowProvider.Microsoft.R.Components.InteractiveWorkflow.IRInteractiveWorkflowVisualProvider.GetOrCreate()
   at Microsoft.VisualStudio.R.Package.Repl.VsRInteractiveWorkflowProvider.Microsoft.R.Components.InteractiveWorkflow.IRInteractiveWorkflowProvider.GetOrCreate()
   at Microsoft.R.Editor.Data.WorkspaceVariableProvider+<UpdateList>d__11.MoveNext()
   at Microsoft.Common.Core.TaskExtensions.ReThrowTaskException(System.Object)
   at Microsoft.Common.Core.TaskExtensions.DoNotWait(System.Threading.Tasks.Task)
   at Microsoft.R.Editor.Data.WorkspaceVariableProvider.SessionMutated()
   at Microsoft.R.Editor.Data.RSessionChangeWatcher.OnSessionMutated(System.Object, System.EventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at Microsoft.R.Host.Client.Session.RSession.OnMutated()
   at Microsoft.R.Host.Client.Session.RSession+<EvaluateAsync>d__98.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions+<ExecuteAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.R.Package.ProjectSystem.RProjectLoadHooks+<>c__DisplayClass22_0+<<ProjectUnloadingAsync>b__0>d.MoveNext()
   at Microsoft.Common.Core.TaskExtensions.ReThrowTaskException(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

### PR DESCRIPTION
**Pull request by AlexanderSher**

### CODE REVIEW

File: src/R/Editor/Impl/Data/WorkspaceVariableProvider.cs [hunk 1]
```diff
@@ -133,9 +137,8 @@ internal sealed class WorkspaceVariableProvider : RSessionChangeWatcher, IVariab
             try {
                 _updating = true;
                 // May be null in tests
-                var session = Workflow.RSession;
-                if (session.IsHostRunning) {
-                    var stackFrames = await session.TracebackAsync();
+                if (Session.IsHostRunning) {
```
Comment (MikhailArkhipov) [inline src/R/Editor/Impl/Data/WorkspaceVariableProvider.cs]: I think there may also be a problem if session gets disposed between async calls below. May be worth catching disposed exception too.

**Comment by MikhailArkhipov** [comment]
👍

File: src/R/Editor/Impl/Data/WorkspaceVariableProvider.cs (hunk 1 above)
Comment (AlexanderSher) [reply src/R/Editor/Impl/Data/WorkspaceVariableProvider.cs]: AFAIK `RHost` doesn't throw `ObjectDisposedException`. When connection is terminated, it throws `RHostDisconnectedException`, which is derived from `OperationCanceledException` and so it will be swallowed by `DoNotWait`.
