### PR TITLE
Two bug fixes

### LINKED ISSUE #4164: Can't reconnect to externally stopped container
- Create docker container
- Connect to container 
- Stop container from powershell
- Connect to container using double-click on containers tool window

**Actual:** RTVS shows an error that connection is established already
**Expected:** RTVS is connected to container

### LINKED ISSUE #4165: Create button is still disabled all fields are correctly filled in "From Template" tab

### PR DESCRIPTION
**Pull request by AlexanderSher**
- Fix #4164: Can't reconnect to externally stopped container
- Fix #4165: Create button is still disabled all fields are correctly filled in "From Template" tab

### CODE REVIEW

File: src/Windows/R/Components/Impl/ContainerManager/Implementation/ViewModel/CreateLocalDockerFromFileViewModel.cs [hunk 1]
```diff
@@ -13,6 +13,7 @@ internal sealed class CreateLocalDockerFromFileViewModel : CreateLocalDockerView
             set {
                 if (SetProperty(ref _templatePath, value)) {
                     IsTemplatePathValid = Uri.TryCreate(value, UriKind.Absolute, out _);
+                    UpdateIsValid();
```
Comment (AlexanderSher) [inline src/Windows/R/Components/Impl/ContainerManager/Implementation/ViewModel/CreateLocalDockerFromFileViewModel.cs]: This is a fix for #4165. The rest is for the #4164.

**Comment by MikhailArkhipov** [comment]
:+1

**Comment by MikhailArkhipov** [comment]
OK, phone doesn’t let emoji
