### PR TITLE
Fixes #2487 bunch of fixes

### LINKED ISSUE #2487: Remote installer issues
1. Installer needs a default broker config file.
2. Add monitor process to start-up
3. User service status signal APIs to let windows know that service is starting/stopping.

### PR DESCRIPTION
**Pull request by karthiknadig**
Added json config file for broker.
Added code to autostart monitor.
Adds status info for the user profile service.

### CODE REVIEW

File: src/Host/Broker/Impl/Microsoft.R.Host.Broker.Config.json [hunk 1]
```diff
@@ -0,0 +1,3 @@
+﻿{
+  "server.urls": "https://0.0.0.0:5000"
```
Comment (int19h) [inline src/Host/Broker/Impl/Microsoft.R.Host.Broker.Config.json]: Now that we're actually configuring the port out of the box, instead of letting the user do so, let's pick something better - 5000 is the default for all ASP.NET Core apps. 

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt

File: src/Host/UserProfile/Impl/Program.cs [hunk 2]
```diff
@@ -12,7 +12,7 @@ static class Program {
         static void Main() {
 #if DEBUG
             // Uncomment the line below to debug the Broker-Service
-            // Debugger.Launch();
+            Debugger.Launch();
```
Comment (int19h) [inline src/Host/UserProfile/Impl/Program.cs]: This should stay commented by default.

File: src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj [hunk 3]
```diff
@@ -173,6 +173,9 @@
       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
       <Visible>True</Visible>
     </Content>
+    <None Include="Microsoft.R.Host.Broker.Config.json">
+      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
```
Comment (int19h) [inline src/Host/Broker/Impl/Microsoft.R.Host.Broker.csproj]: This should be "Newer" to avoid F5 always doing a rebuild.

**Comment by int19h** [comment]
👍
