### PR TITLE
Fix three bugs + simplify RSession initialization logic

### LINKED ISSUE #2802: Move RSession._initializationTcs.SetResult  from IRCallbacks.Connected to IRCallbacks.ReadConsole
RSession may be considered fully initialized only when it is ready to accept input.

### LINKED ISSUE #2858: Package manager crash
```
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.R.Host.Client.REvaluationException
   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions.ThrowOnError(System.String, Microsoft.R.Host.Client.REvaluationResult)
   at Microsoft.R.Host.Client.RExpressionEvaluatorExtensions+<ExecuteAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Host.Client.Session.RSessionEvaluationCommands+<SetVsCranSelectionAsync>d__34.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Components.PackageManager.Implementation.RPackageManager+<GetPackagesAsync>d__32.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Components.PackageManager.Implementation.RPackageManager+<GetAvailablePackagesAsync>d__23.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Components.PackageManager.Implementation.ViewModel.RPackageManagerViewModel+<LoadAvailablePackagesAsync>d__52.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.R.Components.PackageManager.Implementation.ViewModel.RPackageManagerViewModel+<EnsureAvailablePackagesLoadedAsync>d__51.MoveNext()
   at Microsoft.Common.Core.TaskExtensions+<>c.<DoNotWaitThreadContinuation>b__6_0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

### LINKED ISSUE #2888: _cts.Cancel() in RHost.RunWorker may lead to the deadlock in VisualGridScroller
```cs
Microsoft.VisualStudio.R.Package.dll!Microsoft.VisualStudio.R.Package.DataInspect.VisualGridScroller.ScrollCommandsHandler(System.Threading.CancellationToken cancellationToken) Line 69	C#
Microsoft.VisualStudio.R.Package.dll!Microsoft.VisualStudio.R.Package.DataInspect.DataSource.GridDataSource.GetGridDataAsync(Microsoft.R.Host.Client.IRSession rSession, string expression, Microsoft.VisualStudio.R.Package.DataInspect.GridRange? gridRange, Microsoft.VisualStudio.R.Package.DataInspect.ISortOrder sortOrder) Line 28	C#
Microsoft.R.Host.Client.dll!Microsoft.R.Host.Client.RExpressionEvaluatorExtensions.EvaluateAsync<Microsoft.VisualStudio.R.Package.DataInspect.GridData>(Microsoft.R.Host.Client.IRExpressionEvaluator evaluator, string expression, Microsoft.R.Host.Client.REvaluationKind kind, System.Threading.CancellationToken cancellationToken) Line 96	C#
Microsoft.R.Host.Client.dll!Microsoft.R.Host.Client.Session.RSession.EvaluateAsync(string expression, Microsoft.R.Host.Client.REvaluationKind kind, bool waitUntilInitialized, System.Threading.CancellationToken cancellationToken) Line 159	C#
Microsoft.R.Host.Client.dll!Microsoft.R.Host.Client.RHost.EvaluateAsync(string expression, Microsoft.R.Host.Client.REvaluationKind kind, System.Threading.CancellationToken cancellationToken) Line 311	C#
Microsoft.R.Common.Core.dll!Microsoft.Common.Core.TaskCompletionSourceExtensions.CancelOnTokenAction<Microsoft.R.Host.Client.REvaluationResult>.Invoke() Line 25	C#
Microsoft.R.Host.Client.dll!Microsoft.R.Host.Client.RHost.RunWorker(System.Threading.CancellationToken ct) Line 597	C#
```

### PR DESCRIPTION
**Pull request by AlexanderSher**
- Fix #2858: Package manager crash
- Fix #2802: Move RSession._initializationTcs.SetResult from IRCallbacks.Connected to IRCallbacks.ReadConsole
- Fix #2888: _cts.Cancel() in RHost.RunWorker may lead to the deadlock in VisualGridScroller

### CODE REVIEW

**Comment by MikhailArkhipov** [comment]
👍

File: src/Host/Client/Impl/Session/RSession.cs [hunk 1]
```diff
@@ -369,116 +364,117 @@ public Task StartHostAsync(RHostStartupInfo startupInfo, IRSessionCallback callb
...
-                    // below calls may depend on functions exposed from the RTVS package
-                    var libPath = IsRemote ? "." : Path.GetDirectoryName(Assembly.GetExecutingAssembly().GetAssemblyPath());
+                // Load RTVS R package before doing anything in R since the calls
+                // below calls may depend on functions exposed from the RTVS package
+                var libPath = IsRemote ? "." : Path.GetDirectoryName(Assembly.GetExecutingAssembly().GetAssemblyPath());
 
-                    await LoadRtvsPackage(evaluation, libPath);
+                await LoadRtvsPackage(evaluator, libPath);
 
                     var wd = startupInfo.WorkingDirectory;
```
Comment (int19h) [inline src/Host/Client/Impl/Session/RSession.cs]: Looks like the merge messed up indentation here.

**Comment by int19h** [comment]
👍
