### PR TITLE
Fixes grid data when it includes NA values.

### LINKED ISSUE #2053: No data viewer
Hello, 

When I want see my data clicking in the Variable Explorer or with "View(data)", nothing is shown (like in the image).

image

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.10586.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.4.20623.1711, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\R Client\R_SERVER\

### PR DESCRIPTION
**Pull request by huguesv**
Fix #2053 No data viewer

### CODE REVIEW

File: src/Package/Test/DataInspect/EvaluationWrapperTest.cs [hunk 1]
```diff
@@ -453,6 +453,41 @@ public class EvaluationWrapperTest {
 
         [Test]
         [Category.Variable.Explorer]
+        public async Task DataFrameNATest() {
```
Comment (int19h) [inline src/Package/Test/DataInspect/EvaluationWrapperTest.cs]: Can you make it a test in `GridDataTest` class instead? This one I consider legacy code, because it takes way more dependencies than it actually needs to tests what it's testing - the only reason why it's still around is because I didn't have time to port all the tests from here to there.

**Comment by huguesv** [comment]
Moved test.

**Comment by int19h** [comment]
:+1:
