### PR TITLE
- Fix #1151: Improve file system watching mechanism

### LINKED ISSUE #658: Assertion in File Watcher: The data area passed to a system call is too small
I just saw this for the first time, when loading an existing project.  I've been using that project for a while, unmodified, without issues.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Error in File Watcher:
System.ComponentModel.Win32Exception (0x80004005): The data area passed to a system call is too small



   at Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.IO.MsBuildFileSystemWatcher.TraceError(String watcherName, ErrorEventArgs errorEventArgs) in C:\Projects\GitHub\huguesv\RTVS\errorhandling\RTVS\src\ProjectSystem\Impl\IO\MsBuildFileSystemWatcher.cs:line 165

   at Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.IO.MsBuildFileSystemWatcher.<Start>b__22_3(Object sender, ErrorEventArgs e) in C:\Projects\GitHub\huguesv\RTVS\errorhandling\RTVS\src\ProjectSystem\Impl\IO\MsBuildFileSystemWatcher.cs:line 69

   at System.IO.FileSystemWatcher.OnError(ErrorEventArgs e)

   at System.IO.FileSystemWatcher.Monitor(Byte[] buffer)

   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)

   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

Dump and logs here:
\\pytools\RollData\RTVS\Bugs\Hugues-FileWatcher-DataAreaTooSmall

### LINKED ISSUE #1151: Improve file system watching mechanism
Several issues have to be addressed:
- Multiple rename/add/delete sequences may cause incorrect file status
- Delete of network share causes System.IO.InternalBufferOverflowException
- If connection to the network share is lost, FileSystemWatcher stops monitoring and doesn't start working when connection is restored

### LINKED ISSUE #1269: Save As file into the project folder doesn't update SolutionExplorer
Open R project
Open R script (say, foo.r)
Save As, foo1.r

Observed: Solution explorer doesn't show foo1.r

Click 'Show all files'

Observed: foo1.r is visible now

### PR DESCRIPTION
**Pull request by AlexanderSher**
- Fix #658: Assertion in File Watcher: The data area passed to a system call is too small
- Fix #1269: Save As file into the project folder doesn't update SolutionExplorer

### CODE REVIEW

File: src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.DirectoryRenamed.cs [hunk 1]
```diff
@@ -26,40 +29,42 @@ private class DirectoryRenamed : IFileSystemChange {
...
                 var oldRelativePath = PathHelper.EnsureTrailingSlash(PathHelper.MakeRelative(_rootDirectory, _oldFullPath));
+                var newRelativePaths = _entries.RenameDirectory(oldRelativePath, newRelativePath);
 
-                // If directory with the oldRelativePath was previously added, remove it from the AddedDirectories, add newRelativePath and change all its content paths:
-                if (changeset.AddedDirectories.Contains(oldRelativePath)) {
-                    UpdatePrefix(changeset.AddedDirectories, oldRelativePath, newRelativePath);
-                    UpdatePrefix(changeset.AddedFiles, oldRelativePath, newRelativePath);
-                    return;
-                }
+                //// If directory with the oldRelativePath was previously added, remove it from the AddedDirectories, add newRelativePath and change all its content paths:
```
Comment (int19h) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.DirectoryRenamed.cs]: Is this commented out temporarily?

File: src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcherEntries.cs [hunk 2]
```diff
@@ -0,0 +1,323 @@
+using System;
```
Comment (int19h) [inline src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcherEntries.cs]: Needs the copyright header.

File: src/ProjectSystem/Test/Assertions/MsBuildFileSystemWatcherChangesetAssertions.cs [hunk 3]
```diff
@@ -0,0 +1,204 @@
+﻿using System.Collections.Generic;
```
Comment (int19h) [inline src/ProjectSystem/Test/Assertions/MsBuildFileSystemWatcherChangesetAssertions.cs]: Copyright header.

File: src/ProjectSystem/Test/IO/MsBuildFileSystemWatcherEntriesTest.cs [hunk 4]
```diff
@@ -0,0 +1,190 @@
+﻿using Microsoft.UnitTests.Core.XUnit;
```
Comment (int19h) [inline src/ProjectSystem/Test/IO/MsBuildFileSystemWatcherEntriesTest.cs]: Copyright header.

File: src/UnitTests/Core/Impl/FluentAssertions/GivenSelectorExtensions.cs [hunk 5]
```diff
@@ -0,0 +1,155 @@
+﻿using System;
```
Comment (int19h) [inline src/UnitTests/Core/Impl/FluentAssertions/GivenSelectorExtensions.cs]: Copyright.

**Comment by int19h** [comment]
:+1:
