### PR TITLE
R Markdown brace matching + #3623

### LINKED ISSUE #3623: NRE in SmartIndenter
`editorBuffer` is null.

StackTrace:
```cs
Microsoft.R.Editor.dll!Microsoft.R.Editor.SmartIndent.SmartIndenter.GetSmartIndent(Microsoft.Languages.Editor.Text.IEditorLine line, Microsoft.R.Editor.IREditorSettings settings, Microsoft.R.Core.AST.AstRoot ast, int originalIndentSizeInSpaces, bool formatting) Line 95	C# Microsoft.R.Editor.dll!Microsoft.R.Editor.SmartIndent.SmartIndenter.GetDesiredIndentation(Microsoft.Languages.Editor.Text.IEditorLine line, Microsoft.Languages.Core.Formatting.IndentStyle indentStyle) Line 50	C# 	Microsoft.R.Editor.dll!Microsoft.R.Editor.SmartIndent.SmartIndenter.GetDesiredIndentation(Microsoft.Languages.Editor.Text.IEditorLine line) Line 31	C#
Microsoft.R.Editor.Windows.dll!Microsoft.R.Editor.SmartIndent.SmartIndent.GetDesiredIndentation(Microsoft.VisualStudio.Text.ITextSnapshotLine line) Line 19	C#
Microsoft.VisualStudio.InteractiveWindow.dll!Microsoft.VisualStudio.InteractiveWindow.InteractiveSmartIndenter.GetDesiredIndentation(Microsoft.VisualStudio.Text.ITextSnapshotLine line)	Unknown
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Editor.Implementation.SmartIndentationService.GetDesiredIndentation(Microsoft.VisualStudio.Text.Editor.ITextView textView, Microsoft.VisualStudio.Text.ITextSnapshotLine line)	Unknown
Microsoft.VisualStudio.InteractiveWindow.dll!Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThreadOnly.IndentCurrentLine(Microsoft.VisualStudio.Text.SnapshotPoint caretPosition)	Unknown
Microsoft.VisualStudio.InteractiveWindow.dll!Microsoft.VisualStudio.InteractiveWindow.InteractiveWindow.UIThreadOnly.CaretPositionChanged(object sender, Microsoft.VisualStudio.Text.Editor.CaretPositionChangedEventArgs e)	Unknown
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent<Microsoft.VisualStudio.Text.Editor.CaretPositionChangedEventArgs>(object sender, System.EventHandler<Microsoft.VisualStudio.Text.Editor.CaretPositionChangedEventArgs> eventHandlers, Microsoft.VisualStudio.Text.Editor.CaretPositionChangedEventArgs args)	Unknown
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.InternalMoveCaret(Microsoft.VisualStudio.Text.VirtualSnapshotPoint bufferPosition, Microsoft.VisualStudio.Text.PositionAffinity caretAffinity, Microsoft.VisualStudio.Text.Formatting.ITextViewLine textLine, bool captureHorizontalPosition, bool captureVerticalPosition, bool raiseEvent)	Unknown
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.InternalMoveCaretToTextViewLine(Microsoft.VisualStudio.Text.Formatting.ITextViewLine textLine, double xCoordinate, bool allowPlacementInVirtualSpace, bool captureHorizontalPosition, bool captureVerticalPosition, bool raiseEvent)	Unknown
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.MoveTo(Microsoft.VisualStudio.Text.Formatting.ITextViewLine textLine, double xCoordinate, bool captureHorizontalPosition)	Unknown
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.MoveTo(Microsoft.VisualStudio.Text.Formatting.ITextViewLine textLine, double xCoordinate)	Unknown
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Operations.Implementation.EditorOperations.MoveCaret(Microsoft.VisualStudio.Text.Formatting.ITextViewLine textLine, double horizontalOffset, bool extendSelection)	Unknown
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Editor.Implementation.MasterMouseProcessor.HandleMouseLeftButtonDown(bool shift, bool alt, System.Windows.Point pt)	Unknown
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Editor.Implementation.MasterMouseProcessor.DefaultMouseLeftButtonDownHandler(object sender, System.Windows.Input.MouseButtonEventArgs e)	Unknown
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor.UIElement_MouseLeftButtonDown.AnonymousMethod__1()	Unknown
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor.MouseProcessorHandler(System.Windows.RoutedEventArgs e, System.Action<Microsoft.VisualStudio.Text.Editor.IMouseProcessor> preprocess, System.Action defaultAction, System.Action<Microsoft.VisualStudio.Text.Editor.IMouseProcessor> postprocess)	Unknown
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor.UIElement_MouseLeftButtonDown(object sender, System.Windows.Input.MouseButtonEventArgs e)	Unknown
```

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fix #3623 
R Markdown brace matching/highlight
Install `rmarkdown` rather than complain

### CODE REVIEW

File: src/Languages/Core/Test/Braces/BraceTokenizerTest.cs [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+using Microsoft.UnitTests.Core.XUnit;
+using Xunit;
+
+namespace Microsoft.Languages.Core.Test.Braces {
+    [ExcludeFromCodeCoverage]
+    [Category.Languages.Core]
+    public sealed class BraceTokenizerTest {
+        [CompositeTest]
+        [InlineData("", new BraceTokenType[0])]
+        [InlineData("func()[x]{}", new[] { BraceTokenType.OpenBrace, BraceTokenType.CloseBrace, BraceTokenType.OpenBracket, BraceTokenType.CloseBracket, BraceTokenType.OpenCurly, BraceTokenType.CloseCurly })]
```
Comment (AlexanderSher) [inline src/Languages/Core/Test/Braces/BraceTokenizerTest.cs]: you can add `using static BraceTokenType` to avoid adding `BraceTokenType` for every enum value

File: src/Windows/Editor/Impl/Text/EditorBufferSnapshot.cs [hunk 2]
```diff
@@ -7,21 +7,24 @@
...
+        public EditorBufferSnapshot(ITextSnapshot snapshot) : base(snapshot) {
             _snapshot = snapshot;
         }
 
-        public T As<T>() where T:class => _snapshot as T;
-        public IEditorBuffer EditorBuffer => _snapshot.TextBuffer.ToEditorBuffer();
+        public T As<T>() where T : class => _snapshot as T;
+
+        public IEditorBuffer EditorBuffer
+            => _snapshot.TextBuffer.ToEditorBuffer() ?? new EditorBuffer(_snapshot.TextBuffer);
```
Comment (AlexanderSher) [inline src/Windows/Editor/Impl/Text/EditorBufferSnapshot.cs]: Is it ok to create new instance of `EditorBuffer` every time property is accessed?

File: src/Windows/Markdown/Editor/Impl/Commands/MdCommandFactory.cs [hunk 3]
```diff
@@ -15,16 +18,20 @@ namespace Microsoft.Markdown.Editor.Commands {
...
     [ContentType(MdContentTypeDefinition.ContentType)]
     internal class MdCommandFactory : ICommandFactory {
+        private readonly IServiceContainer _services;
         private readonly IRInteractiveWorkflowProvider _workflowProvider;
 
         [ImportingConstructor]
-        public MdCommandFactory(IRInteractiveWorkflowProvider workflowProvider) {
-            _workflowProvider = workflowProvider;
+        public MdCommandFactory(ICoreShell coreShell)
+        {
```
Comment (AlexanderSher) [inline src/Windows/Markdown/Editor/Impl/Commands/MdCommandFactory.cs]: Formatting

File: src/Windows/Editor/Impl/Text/EditorBufferSnapshot.cs (hunk 2 above)
Comment (MikhailArkhipov) [inline src/Windows/Editor/Impl/Text/EditorBufferSnapshot.cs]: Generally it is not needed. I guess (from your call stack) may happen that the buffer was never created via the editor. When `EditorBuffer` is created it auto-attached to the text buffer and next `ToEditorBuffer` should use it.

File: src/Windows/Markdown/Editor/Impl/Commands/MdCommandFactory.cs (hunk 3 above)
Comment (MikhailArkhipov) [inline src/Windows/Markdown/Editor/Impl/Commands/MdCommandFactory.cs]: Resharper does not respect VS settings...

Comment (AlexanderSher) [inline src/Windows/Markdown/Editor/Impl/Commands/MdCommandFactory.cs]: Yeah, it has its own settings. Though with at least two R# users, I think we can add a R# settings file to the repo as we did for VS settings. I'll do it.

**Comment by AlexanderSher** [comment]
👍
