### PR TITLE
Fix #2550: Interrupt printing in REPL

### LINKED ISSUE #2550: Interrupt printing in REPL
Sometimes I'll do something stupid like trying to print a 1-million-row data frame. When this happens, the REPL becomes unresponsive, including the Interrupt R button. All I can do is wait until it's finished (it doesn't crash, mind you, which is good).

Would it be possible to interrupt R while it's in the middle of printing?

### PR DESCRIPTION
**Pull request by int19h**
Avoid using DispatchOnUIThread when printing text where possible, to prevent message queue saturation.

### CODE REVIEW

File: src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs [hunk 1]
```diff
@@ -261,26 +262,32 @@ public sealed class RInteractiveEvaluator : IInteractiveEvaluator {
...
+                    // written into the same place.
+                    _lastMessage = message.Substring(1);
+                    _lastPosition = _lastPosition < 0 ? CurrentWindow.OutputBuffer.CurrentSnapshot.Length : _lastPosition;
+                    message = "|"; // replacement placeholder so we can receive 'buffer changed' event
+
                     CurrentWindow.Write(message);
                     CurrentWindow.FlushOutput(); // Must flush so we do get 'buffer changed' immediately.
+                });
+            } else {
+                if (_lastMessage != null) {
```
Comment (AlexanderSher) [inline src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs]: `_lastMessage` has to be volatile

Comment (int19h) [inline src/R/Components/Impl/InteractiveWorkflow/Implementation/RInteractiveEvaluator.cs]: Fixed.

**Comment by AlexanderSher** [comment]
👍
