### PR TITLE
Three bug fixes

### LINKED ISSUE #3938: Containers "start" button should be disabled for busy ports
`IContainer` has information about its ports. We can disable "start" button for containers with same ports if one of them is running.

### LINKED ISSUE #4006: Renaming connection to container makes it go to Local
Create container
Rename connection
Went to local

### LINKED ISSUE #4007: Container connection properties should show container info
OR it should not be possible to rename it - see #4006. Better if it is possible to rename it but user would see name of the container.

### PR DESCRIPTION
**Pull request by AlexanderSher**
- Fix #3938: Containers "start" button should be disabled for busy ports
- Fix #4006: Renaming connection to container makes it go to Local
- Fix #4007: Container connection properties should show container info

### CODE REVIEW

File: src/R/Components/Impl/ConnectionManager/IConnection.cs [hunk 1]
```diff
@@ -10,6 +10,8 @@ public interface IConnection: IConnectionInfo {
 
         Uri Uri { get; }
 
+        string ContainerName { get; }
```
Comment (MikhailArkhipov) [inline src/R/Components/Impl/ConnectionManager/IConnection.cs]: Does it need to be pesistent? May need to go to `IConnectionInfo`

File: src/Windows/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs [hunk 2]
```diff
@@ -326,13 +326,12 @@ internal sealed class ConnectionManagerViewModel : ConnectionStatusBaseViewModel
                 _localDockerConnections.Clear();
                 _remoteConnections.Clear();
                 foreach (var connection in ConnectionManager.RecentConnections.OrderBy(c => c.Name)) {
-                    var cvm = CreateConnectionViewModel(connection);
                     if (connection.IsRemote) {
```
Comment (MikhailArkhipov) [inline src/Windows/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs]: Prob will benefit from some class derivation and virtual factories, but OK for now

File: src/Windows/R/Components/Impl/Resources.resx [hunk 3]
```diff
@@ -348,6 +348,9 @@
   <data name="ConnectionManager_EditLocalTooltip_Format" xml:space="preserve">
     <value>Edit local connection '{0}'</value>
   </data>
+  <data name="ConnectionManager_EditLocalDockerTooltip_Format" xml:space="preserve">
+    <value>Edit local docker connection '{0}'</value>
```
Comment (MikhailArkhipov) [inline src/Windows/R/Components/Impl/Resources.resx]: Docker is trademark so probably needs to be capitalized. ex Wikipedia `Because Docker containers are so lightweight...`

**Comment by MikhailArkhipov** [comment]
Need to fix `docker` -> `Docker`
👍

File: src/R/Components/Impl/ConnectionManager/IConnection.cs (hunk 1 above)
Comment (AlexanderSher) [reply src/R/Components/Impl/ConnectionManager/IConnection.cs]: Dunno. We can always find out if it is a docker connection or not by inspecting docker ports.

File: src/Windows/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs (hunk 2 above)
Comment (AlexanderSher) [reply src/Windows/R/Components/Impl/ConnectionManager/Implementation/ViewModel/ConnectionManagerViewModel.cs]: Not just factories, but actually types that handle different types of operations. #4029

File: src/Windows/R/Components/Impl/Resources.resx (hunk 3 above)
Comment (AlexanderSher) [reply src/Windows/R/Components/Impl/Resources.resx]: Ok
